### ISSUE TITLE
First analysis on a "non-main branch" is not processed/displayed in sonarqube 10.6 when the project is auto-provisioned

### ISSUE THREAD

**Issue by Jidus** [mc1arke/sonarqube-community-branch-plugin#1005]
**Describe the bug**
The first analysis on a "non-main branch" is not processed/displayed in sonarqube 10.6 when the project is auto-provisioned.
("non-main branch" => as configured in "Branches & Pull Requests" project settings tab)

**To Reproduce**
On an WSL/ubuntu host
1. Install a classic sonarqube 10.6 instance via its docker image. Map volume/folders
```
docker run \
--name sonarqube \
--network=host \
-p 9000:9000 \
-v mappings ...
sonarqube:10.6.0-community 
```

2. Download Community Branch Plugin 1.22.0 jar file from Github Project Release page. Move it to the `extensions/plugins/` folder of sonarqube container

3. Configure sonar.properties file, in container's `conf/` folder, by adding folowing lines :
```
# additional conf for branch plugin
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.22.0.jar=ce
```

4. Restart sonarqube container

5. Verify that "main" is the "Default main branch name" in General settings

6. On same host, cd into your code to analyse

7. Launch a sonar scan on a **non-existing project** and **non-main branch** via
```
docker run --rm \
--network=host \
-e SONAR_HOST_URL="http://localhost:9000"  \
-v "$(pwd):/usr/src" \
sonarsource/sonar-scanner-cli:latest \
-Dsonar.projectKey=non_existing_project \
-Dsonar.projectName=non_existing_project \
-Dsonar.token=***generated_admin_token*** \
-Dsonar.branch.name=my_custom_branch
```

**Expected behavior**
Project is created and we should see analysis results on the _my_custom_branch_ branch of the project view in sonar. 

**Obtained behavior**
Project is created BUT analysis is not populated in branch page.
We only get a message '"my_custom_branch" branch has not been analyzed yet.' in the branch analysis page.

**Screenshots**
Expected results
![image](https://github.com/user-attachments/assets/8cbb945e-2983-4947-af67-4a25ad628aac)

Obtained results
![image](https://github.com/user-attachments/assets/34a11839-6056-454d-89e1-21c8c78c24e7)

**Software Versions**
 - SonarQube Version: 10.6 community
 - Plugin Version: 1.22.0
 - Sonar scanner : "latest" tag

**Additional context**
I suspect this behaviour is the cause why in Jenkins, our "waitForQualityGate" call crash (via Jenkins Sonar Plugin) after scan
We need to launch a second time the same sonar scanner command line to populate the branch analysis, as expected.

The same usecase, but without branch parameter OR "main" (as it) reference branch submitted in scanner command line, gives us analysis results in sonarqube at first call (as expected)

Don't hesitate to ask me if you need more info on this case.

Thanks

**Comment by mc1arke** [comment]
Do you get an error in the logs on the first analysis?

**Comment by Jidus** [comment]
In the scanner logs, I can see no errors : 
```
15:24:48.835 INFO  Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
15:24:48.837 INFO  Project root configuration file: NONE
15:24:48.848 INFO  SonarScanner CLI 6.2.1.4610
15:24:48.849 INFO  Java 17.0.12 Amazon.com Inc. (64-bit)
15:24:48.850 INFO  Linux 5.10.102.1-microsoft-standard-WSL2 amd64
15:24:48.867 INFO  User cache: /opt/sonar-scanner/.sonar/cache
15:24:49.385 INFO  JRE provisioning: os[linux], arch[x86_64]
15:24:50.541 INFO  Communicating with SonarQube Server 10.6.0.92116
15:24:50.732 INFO  Starting SonarScanner Engine...
15:24:50.733 INFO  Java 17.0.11 Eclipse Adoptium (64-bit)
15:24:51.344 INFO  Load global settings
15:24:51.412 INFO  Load global settings (done) | time=68ms
15:24:51.414 INFO  Server id: 147B411E-AZNODqEI4-4ta4G7k3-C
15:24:51.423 INFO  Loading required plugins
15:24:51.423 INFO  Load plugins index
15:24:51.444 INFO  Load plugins index (done) | time=20ms
15:24:51.445 INFO  Load/download plugins
15:24:51.880 INFO  Load/download plugins (done) | time=435ms
15:24:52.127 INFO  Process project properties
15:24:52.127 INFO  Process project properties (done) | time=0ms
15:24:52.133 INFO  Project key: non_existing_project
15:24:52.133 INFO  Base dir: /usr/src
15:24:52.134 INFO  Working dir: /tmp/.scannerwork
15:24:52.142 INFO  Load project settings for component key: 'non_existing_project'
15:24:52.171 INFO  Load project branches
15:24:52.178 INFO  Load project branches (done) | time=7ms
15:24:52.179 INFO  Load branch configuration
15:24:52.181 INFO  Load branch configuration (done) | time=2ms
15:24:52.193 INFO  Load quality profiles
15:24:52.366 INFO  Load quality profiles (done) | time=174ms
15:24:52.406 INFO  Load active rules
15:24:58.701 INFO  Load active rules (done) | time=6295ms
15:24:58.705 INFO  Load analysis cache
15:24:58.711 INFO  Load analysis cache (404) | time=7ms
15:24:58.739 INFO  Branch name: my_custom_branch
15:24:58.753 INFO  Preprocessing files...
15:24:58.849 INFO  1 language detected in 23 preprocessed files
15:24:58.850 INFO  8 files ignored because of scm ignore settings
15:24:58.851 INFO  Loading plugins for detected languages
15:24:58.852 INFO  Load/download plugins
15:24:59.267 INFO  Load/download plugins (done) | time=416ms
15:24:59.356 INFO  Load project repositories
15:24:59.363 INFO  Load project repositories (done) | time=7ms
15:24:59.378 INFO  Indexing files...
15:24:59.378 INFO  Project configuration:
15:24:59.393 INFO  23 files indexed
15:24:59.394 INFO  Quality profile for yaml: Sonar way
15:24:59.394 INFO  ------------- Run sensors on module non_existing_project
15:24:59.429 INFO  Load metrics repository
15:24:59.445 INFO  Load metrics repository (done) | time=15ms
15:24:59.791 INFO  Sensor JaCoCo XML Report Importer [jacoco]
15:24:59.792 INFO  'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
15:24:59.793 INFO  No report imported, no coverage information will be imported by JaCoCo XML Report Importer
15:24:59.793 INFO  Sensor JaCoCo XML Report Importer [jacoco] (done) | time=1ms
15:24:59.794 INFO  Sensor IaC CloudFormation Sensor [iac]
15:24:59.825 INFO  2 source files to be analyzed
15:25:00.070 INFO  2/2 source files have been analyzed
15:25:00.071 INFO  Sensor IaC CloudFormation Sensor [iac] (done) | time=278ms
15:25:00.071 INFO  Sensor IaC Kubernetes Sensor [iac]
15:25:00.122 INFO  0 source files to be analyzed
15:25:00.126 INFO  0/0 source files have been analyzed
15:25:00.126 INFO  Sensor IaC Kubernetes Sensor [iac] (done) | time=56ms
15:25:00.126 INFO  Sensor Java Config Sensor [iac]
15:25:00.128 INFO  0 source files to be analyzed
15:25:00.132 INFO  0/0 source files have been analyzed
15:25:00.132 INFO  Sensor Java Config Sensor [iac] (done) | time=6ms
15:25:00.132 INFO  Sensor com.github.mc1arke.sonarqube.plugin.scanner.ScannerPullRequestPropertySensor
15:25:00.132 INFO  Sensor com.github.mc1arke.sonarqube.plugin.scanner.ScannerPullRequestPropertySensor (done) | time=0ms
15:25:00.132 INFO  Sensor JavaScript inside YAML analysis [javascript]
15:25:00.148 INFO  No input files found for analysis
15:25:00.149 INFO  Hit the cache for 0 out of 0
15:25:00.149 INFO  Miss the cache for 0 out of 0
15:25:00.150 INFO  Sensor JavaScript inside YAML analysis [javascript] (done) | time=17ms
15:25:00.150 INFO  Sensor CSS Rules [javascript]
15:25:00.150 INFO  No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
15:25:00.151 INFO  Sensor CSS Rules [javascript] (done) | time=0ms
15:25:00.151 INFO  Sensor IaC Docker Sensor [iac]
15:25:00.151 INFO  0 source files to be analyzed
15:25:00.197 INFO  0/0 source files have been analyzed
15:25:00.198 INFO  Sensor IaC Docker Sensor [iac] (done) | time=47ms
15:25:00.198 INFO  Sensor TextAndSecretsSensor [text]
15:25:00.198 INFO  Available processors: 20
15:25:00.198 INFO  Using 20 threads for analysis.
15:25:00.491 INFO  The property "sonar.tests" is not set. To improve the analysis accuracy, we categorize a file as a test file if any of the following is true:
  * The filename starts with "test"
  * The filename contains "test." or "tests."
  * Any directory in the file path is named: "doc", "docs", "test" or "tests"
  * Any directory in the file path has a name ending in "test" or "tests"

15:25:00.508 INFO  Using git CLI to retrieve untracked files
15:25:00.523 INFO  Analyzing language associated files and files included via "sonar.text.inclusions" that are tracked by git
15:25:00.547 INFO  10 source files to be analyzed
15:25:00.840 INFO  10/10 source files have been analyzed
15:25:00.842 INFO  Sensor TextAndSecretsSensor [text] (done) | time=645ms
15:25:00.846 INFO  ------------- Run sensors on project
15:25:00.859 INFO  Sensor Zero Coverage Sensor
15:25:00.859 INFO  Sensor Zero Coverage Sensor (done) | time=1ms
15:25:00.860 INFO  SCM Publisher SCM provider for this project is: git
15:25:00.861 INFO  SCM Publisher 2 source files to be analyzed
15:25:01.035 INFO  SCM Publisher 2/2 source files have been analyzed (done) | time=173ms
15:25:01.036 INFO  CPD Executor Calculating CPD for 0 files
15:25:01.036 INFO  CPD Executor CPD calculation finished (done) | time=0ms
15:25:01.040 INFO  SCM revision ID 'e35e91a5f1b8726fce62c4002e652396d2b5aa6d'
15:25:01.102 INFO  Analysis report generated in 61ms, dir size=323.8 kB
15:25:01.115 INFO  Analysis report compressed in 13ms, zip size=51.2 kB
15:25:01.350 INFO  Analysis report uploaded in 235ms
15:25:01.351 INFO  ANALYSIS SUCCESSFUL, you can find the results at: http://localhost:9000/dashboard?id=non_existing_project&branch=my_custom_branch
15:25:01.352 INFO  Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
15:25:01.352 INFO  More about the report processing at http://localhost:9000/api/ce/task?id=af8c5732-4745-47db-9b8c-4f5ed7b9f204
15:25:01.360 INFO  Analysis total time: 9.422 s
15:25:01.360 INFO  SonarScanner Engine completed successfully
15:25:01.691 INFO  EXECUTION SUCCESS
15:25:01.692 INFO  Total time: 12.859s
```

In the Administration/Projects/Background Tasks/Task log Error detail, I can see the following message : 
```
org.sonar.ce.task.projectanalysis.component.VisitException: Visit of Component {key=non_existing_project:src/artifact/templates/02_principal.yaml,type=FILE} failed
	at org.sonar.ce.task.projectanalysis.component.VisitException.rethrowOrWrap(VisitException.java:44)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:71)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitChildren(VisitorsCrawler.java:107)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:94)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitChildren(VisitorsCrawler.java:107)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:94)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
	at org.sonar.ce.task.projectanalysis.step.ExecuteVisitorsStep.execute(ExecuteVisitorsStep.java:51)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:79)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:70)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:57)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Fail to process issues of component 'non_existing_project:src/artifact/templates/02_principal.yaml'
	at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.visitAny(IntegrateIssuesVisitor.java:107)
	at org.sonar.ce.task.projectanalysis.component.TypeAwareVisitorWrapper.visitAny(TypeAwareVisitorWrapper.java:77)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitNode(VisitorsCrawler.java:114)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:97)
	at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
	... 26 more
Caused by: java.lang.IllegalStateException: Reference branch 'd4538f14-8bba-4539-bb0f-2ec08d48d4de' does not exist
	at com.google.common.base.Preconditions.checkState(Preconditions.java:604)
	at org.sonar.ce.task.projectanalysis.component.ReferenceBranchComponentUuids.lazyInit(ReferenceBranchComponentUuids.java:59)
	at org.sonar.ce.task.projectanalysis.component.ReferenceBranchComponentUuids.getComponentUuid(ReferenceBranchComponentUuids.java:90)
	at org.sonar.ce.task.projectanalysis.issue.TrackerReferenceBranchInputFactory.create(TrackerReferenceBranchInputFactory.java:49)
	at org.sonar.ce.task.projectanalysis.issue.ReferenceBranchTrackerExecution.track(ReferenceBranchTrackerExecution.java:38)
	at org.sonar.ce.task.projectanalysis.issue.IssueTrackingDelegator.track(IssueTrackingDelegator.java:52)
	at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.getRawIssues(IntegrateIssuesVisitor.java:154)
	at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.getIssues(IntegrateIssuesVisitor.java:124)
	at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.visitAny(IntegrateIssuesVisitor.java:98)
	... 30 more
```

Don't hesitate to tell me if you need more infos

Thanks

**Comment by csongs** [comment]
I encountered the same error.

The SonarQube server is running Community Edition v10.7 (96327).

However, when I ran the scan a second time, it worked fine.

**Comment by Moving-from-Russia** [comment]
Hello!
I have encountered the same error.

Sonarqube version - 10.6 (92116)
The plugin version for the community branch is 1.21.0

When you first launch a new project and a branch that differs from the default branch, SonarQube does not provide analysis and an error occurs. A page with a project and two branches is being created, but there is no analysis.

Error Details:
```
org.sonar.ce.task.projectanalysis.component.VisitException: Visit of Component {key=rim-webui:src/rim-webui/src/components/KebabActKC2/index.ts,type=FILE} failed
  at org.sonar.ce.task.projectanalysis.component.VisitException.rethrowOrWrap(VisitException.java:44)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:71)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitChildren(VisitorsCrawler.java:107)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:94)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitChildren(VisitorsCrawler.java:107)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:94)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitChildren(VisitorsCrawler.java:107)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:94)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitChildren(VisitorsCrawler.java:107)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:94)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitChildren(VisitorsCrawler.java:107)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:94)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
  at org.sonar.ce.task.projectanalysis.step.ExecuteVisitorsStep.execute(ExecuteVisitorsStep.java:51)
  at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:79)
  at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:70)
  at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:57)
  at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
  at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
  at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
  at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
  at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
  at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
  at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
  at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
  at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
  at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Fail to process issues of component 'rim-webui:src/rim-webui/src/components/KebabActKC2/index.ts'
  at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.visitAny(IntegrateIssuesVisitor.java:107)
  at org.sonar.ce.task.projectanalysis.component.TypeAwareVisitorWrapper.visitAny(TypeAwareVisitorWrapper.java:77)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitNode(VisitorsCrawler.java:114)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visitImpl(VisitorsCrawler.java:97)
  at org.sonar.ce.task.projectanalysis.component.VisitorsCrawler.visit(VisitorsCrawler.java:69)
  ... 35 more
Caused by: java.lang.IllegalStateException: Reference branch '15810309-1ab4-4c26-b9ee-ba5708c077c1' does not exist
  at com.google.common.base.Preconditions.checkState(Preconditions.java:604)
  at org.sonar.ce.task.projectanalysis.component.ReferenceBranchComponentUuids.lazyInit(ReferenceBranchComponentUuids.java:59)
  at org.sonar.ce.task.projectanalysis.component.ReferenceBranchComponentUuids.getComponentUuid(ReferenceBranchComponentUuids.java:90)
  at org.sonar.ce.task.projectanalysis.issue.TrackerReferenceBranchInputFactory.create(TrackerReferenceBranchInputFactory.java:49)
  at org.sonar.ce.task.projectanalysis.issue.ReferenceBranchTrackerExecution.track(ReferenceBranchTrackerExecution.java:38)
  at org.sonar.ce.task.projectanalysis.issue.IssueTrackingDelegator.track(IssueTrackingDelegator.java:52)
  at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.getRawIssues(IntegrateIssuesVisitor.java:154)
  at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.getIssues(IntegrateIssuesVisitor.java:124)
  at org.sonar.ce.task.projectanalysis.issue.IntegrateIssuesVisitor.visitAny(IntegrateIssuesVisitor.java:98)
  ... 39 more
    
```
When I run the scan a second time, everything works fine

**Comment by Moving-from-Russia** [comment]
UPD
Sonarqube version 10.6 with plugin version 1.21
Sonarqube version 10.5 with plugin version 1.20
Sonarqube version 10.4 with plugin version 1.19
Sonarqube version 10.3 with plugin version 1.18
Sonarqube version 10.2 with plugin version 1.17
It's the same mistake everywhere
Sonarqube version 10.1 with plugin version 1.16 - works without errors

**Comment by bernalvarela** [comment]
It seems that is using the project uuid instead using the branch uuid

![image](https://github.com/user-attachments/assets/2643f62e-e6b5-409f-93b5-1c4474c0490e)

![image](https://github.com/user-attachments/assets/1eaff718-1025-4512-996a-f290debc5e9d)

**Comment by bernalvarela** [comment]
I'm working on a fix for this bug. It seems i have solved the problem.

I make a pr the sooner.

**Comment by mc1arke** [comment]
Fix released in 1.24.0 of the plugin
