### ISSUE TITLE
No commit found for SHA

### ISSUE THREAD

**Issue by lRawd** [mc1arke/sonarqube-community-branch-plugin#116]
If a merge with the target branch is required in a PR, the last Commit ID does not exist in Github and causes the PR decoration to fail.

**Describe the bug**
```
java.lang.IllegalStateException: Could not decorate Pull Request on Github
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:38)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:132)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:113)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:107)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: An error was returned in the response from the Github API:
- Error{message='No commit found for SHA: fbe5ca23fd65381f84a91b2f1920ff08757c5747', locations=[Location{line='1', column='12'}]}
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.v4.GraphqlCheckRunProvider.createCheckRun(GraphqlCheckRunProvider.java:173)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:36)
	... 19 common frames omitted
```

**To Reproduce**
1. Create a branch off Master
2. Add a commit to Master
3. Add a different commit to Branch
4. Create Pull Request

**Expected behavior**
The Pull Request is successfully decorated

**Software Versions**
 - SonarQube Version: 7.9.2.30863
 - Plugin Version: 1.3.1-SNAPSHOT

**Comment by hnioche** [comment]
I have the same issue, iin my case it's due to the fact that Jenkins merges the base branch in the pull request automatically, causing most of the time a merge commit (as soon as the branches diverged and a fast forward is not possible). The commit in question is this merge commit.

**Comment by kennyko** [comment]
I don't believe this plugin does any calculations of the git revision, so I'm not sure how it can be fixed here.

Did a quick search and it looks like this issue also affects the official version and the workaround is to explicitly set the scm.revision property like:
```
sonar.scm.revision=refs/pull/$CHANGE_ID/head
```
to point to the pull request revision, or your own calculated git sha.
See https://community.sonarsource.com/t/pull-requests-analysis-with-github/12885/11

**Comment by hnioche** [comment]
I think it can technically be done in the plugin by passing the SHA of the remote head rather than the local one when calling the GraphQL mutation to create the check. Currently it gets the SHA from the analysis object passed by Sonar which defaults to the local head revision and can be explicitly set as you just said.

I'm not sure that's a good idea though...

**Comment by lRawd** [comment]
I added the following to my jenkinsfile and it is working now:
```
    environment {
        // lookup the last pushed commit so we dont get a local merge commit for sonar
        SONAR_COMMIT = sh(returnStdout: true, script: "git rev-parse refs/remotes/origin/${BRANCH_NAME}").trim();
    }
...
mvn sonar:sonar -Dsonar.scm.revision=${SONAR_COMMIT} ...
```

**Comment by mc1arke** [comment]
Duplicates #104
