### ISSUE TITLE
PR decoration for Bitbucket Server is not stable

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [mc1arke/sonarqube-community-branch-plugin#188]
**Describe the bug**
PR decoration for Bitbucket Server works fine for some time and after that starts to fail with exception in ce.log:

```
2020.06.09 18:40:54 ERROR ce[AXKaYjrN0aO1e6Nbhcdp][c.g.m.s.p.c.p.b.c.BitbucketClient] Could not determine Bitbucket Server version
java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketClient.getServerProperties(BitbucketClient.java:63)
        at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketClient.supportsCodeInsights(BitbucketClient.java:110)
        at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.BitbucketServerPullRequestDecorator.decorateQualityGateStatus(BitbucketServerPullRequestDecorator.java:91)
        at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:139)
        at org.sonar.api.ce.posttask.PostProjectAnalysisTask.finished(PostProjectAnalysisTask.java:63)
        at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:118)
        at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:109)
        at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
        at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
        at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
        at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
        at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
        at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
        at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
        at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
        at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020.06.09 18:40:54 WARN  ce[AXKaYjrN0aO1e6Nbhcdp][c.g.m.s.p.c.p.b.BitbucketServerPullRequestDecorator] Your Bitbucket instances does not support the Code Insights API.
2020.06.09 18:40:54 INFO  ce[AXKaYjrN0aO1e6Nbhcdp][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=SUCCESS | time=20021ms
```

**Workaround**
Restart SonarQube server.

**To Reproduce**
1. Run SonarQube scans for Bitbucket Server pull requests
2. PR decoration works fine for some time then starts to fail
3. Restart SonarQube server
4. PR decoration works fine again for some time then starts to fail

**Expected behavior**
Stable work of PR decoration without SonarQube server restarts.

**Software Versions**
 - SonarQube Version: 8.0
 - Plugin Version: 1.3.1
 - Bitbucket Server 6.5.3

**Additional context**
I saw the same behaviour for 1.3.0 plugin.

**Comment by mc1arke** [comment]
`connect timed out` indicates that your Bitbucket server failed to respond to a connection, in this case the check your Bitbucket server version. Can you confirm if you have any proxies or firewalls between your Sonarqube and Bitbucket servers? Also, have you checked your Bitbucket logs to check it's not reporting any issues at the time?

**Comment by dzmitry-rudnouski** [comment]
Issue is reproduced not so often, trying to catch it and investigate.
