### ISSUE TITLE
Bitbucket cloud decoration fails when more than 100 issues are reported in an anlysis

### ISSUE THREAD

**Issue by mc1arke** [mc1arke/sonarqube-community-branch-plugin#209]
**Describe the bug**
Whilst trying to perform the decoration of a Bitbucket Cloud Pull Request, for an anlalysis with more than 100 open issues, following exception is printed to the logs, and the decoration fails:

```
com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketCloudException: HTTP Status Code: 400; Message:{"code": 400, "message": "Bulk upload supports a maximum of /100 annotations."}
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketCloudClient.validate(BitbucketCloudClient.java:182)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketCloudClient.uploadAnnotations(BitbucketCloudClient.java:115)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.BitbucketPullRequestDecorator.updateAnnotations(BitbucketPullRequestDecorator.java:153)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.BitbucketPullRequestDecorator.decorateQualityGateStatus(BitbucketPullRequestDecorator.java:98)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:160)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:118)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:109)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**To Reproduce**
1. Create a project with a 'clean' branch in Bitbucket and submit it to Sonarqube for scanning
2. Create a second branch from your scanned branch and add over 100 violations to the project (e.g. over 100 lines with `System.err.println("message here");`) raise a pull request, and submit this Pull Request to Sonarqube for analysis
3. Check the ce.log file once the analysis completes to see the above exception, and check the Pull Request for no analysis details having been submitted.

**Expected behavior**
The pull request should contain decoration with all findings, or as many issues as can be reasonably submitted with a warning that the not all issues are annotated

**Screenshots**
n/a

**Software Versions**
 - SonarQube Version: 8.1
 - Plugin Version: Custom Build - master with the 1.3 Bitbucket cloud insights commit cherry-picked across
**Note: ** this should be possibly to replicate with Sonarqube 7.8-8.0 and 1.3.2 of the plugin

**Additional context**
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commit/%7Bcommit%7D/reports/%7BreportId%7D/annotations says `a report can contain up to 1000 annotations` and `You can upload up to 100 annotations per POST request`, so splitting the issues into batches of 100 should overcome this, providing the number of issues is limited to 1000 (or 999 plus an annotation about there being too many issues)

**Comment by mc1arke** [comment]
@marvin-w Let me know if you have time to look at this please

**Comment by marvin-w** [comment]
I'll take care of it

**Comment by marvin-w** [comment]
For Bitbucket Server the following is true:

> A report cannot have more than 1000 annotations by default, however this property is congurable at an instance level. If the request would result in more than the maximum number of annotations being stored then the entire request is rejected and no new annotations are store

**Comment by mc1arke** [comment]
Whoops, I didn't copy this across to master before the 1.5.0 release. I'll include it in 1.6.0 and 1.5.1.
