### ISSUE TITLE
BitbucketCloud PR decaration SQ 7.9 

### ISSUE THREAD

**Issue by KRE100** [mc1arke/sonarqube-community-branch-plugin#281]
SQ server from time-to-time doesn't put a report to the Bitbucket Cloud. Sometimes it happens when you start 2nd build for the existing PR, old report deleted but new one doesn'tput (without any errors in the SQ server). Sometimes SQ return in the logs error. Help me to fix that pls.

```
2020.12.03 15:20:48 ERROR ce[AXYpMPLvMjwHnT0WkNTF][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketCloudException: HTTP Status Code: 404; Message:{"type": "error", "error": {"message": "Resource not found"}}
 at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketCloudClient.validate(BitbucketCloudClient.java:182)
 at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketCloudClient.uploadReport(BitbucketCloudClient.java:138)
 at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.BitbucketPullRequestDecorator.decorateQualityGateStatus(BitbucketPullRequestDecorator.java:107)
 at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:139)
 at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:113)
 at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:107)
 at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
 at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
 at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
 at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
 at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
 at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
 at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
 at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
 at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
 at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
 at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.base/java.lang.Thread.run(Unknown Source)
2020.12.03 15:20:48 INFO  ce[AXYpMPLvMjwHnT0WkNTF][o.s.c.t.CeWorkerImpl] Executed task | project=PLATFORM | type=REPORT | pullRequest=209 | id=AXYpMPLvMjwHnT0WkNTF | submitter=cicd-automation@appknit.io | status=SUCCESS | time=4677ms
```

![image](https://user-images.githubusercontent.com/21992323/101060074-aa64d200-3597-11eb-9a89-c84ea6eeac29.png)

**Software Versions**
 - SonarQube Version: [7.9.3 (build 33349)]
 - Plugin Version: [1.3.2]

**Comment by mc1arke** [comment]
This looks like your Bitbucket server is return a 404 status. Is this issue happening when you do something like rebase a branch or force-push rebased/re-written commits to Bitbucket? I'm assuming that Sonarqube is attempting to decorate a commit that Bitbucket no longer has in the target branch.

**Comment by KRE100** [comment]
I'm working with Bitbucket CLoud, my PRs 100% exists and opened, in most cases it happens when CI server runs not 1st build for PR and I can see next events in SQ server log:
1. delete old SQ report
2. put new one

all steps successfully finished (without error in logs), but new SQ report doesn't publish into PR

**Comment by ivayloc** [comment]
> I'm working with Bitbucket CLoud, my PRs 100% exists and opened, in most cases it happens when CI server runs not 1st build for PR and I can see next events in SQ server log:
> 
> 1. delete old SQ report
> 2. put new one
> 
> all steps successfully finished (without error in logs), but new SQ report doesn't publish into PR

Did you able to fix this issue?

**Comment by KRE100** [comment]
> > I'm working with Bitbucket CLoud, my PRs 100% exists and opened, in most cases it happens when CI server runs not 1st build for PR and I can see next events in SQ server log:
> > 
> > 1. delete old SQ report
> > 2. put new one
> > 
> > all steps successfully finished (without error in logs), but new SQ report doesn't publish into PR
> 
> Did you able to fix this issue?

I didn't. From time to time I'm still getting this issue :-(

**Comment by ivayloc** [comment]
> > > I'm working with Bitbucket CLoud, my PRs 100% exists and opened, in most cases it happens when CI server runs not 1st build for PR and I can see next events in SQ server log:
> > > 
> > > 1. delete old SQ report
> > > 2. put new one
> > > 
> > > all steps successfully finished (without error in logs), but new SQ report doesn't publish into PR
> > 
> > 
> > Did you able to fix this issue?
> 
> I didn't. From time to time I'm still getting this issue :-(

I am actually trying to run the PR decorations for SQ 8.5 with the 1.6 version of the plugin, I have an open issue in StackOverflow - https://stackoverflow.com/questions/65774540/sonarqube-community-branch-plugin-pull-request-decorations-are-not-working, I know you are using SQ7.9 but can you take a look at my configuration maybe I am missing something more general?

**Comment by mc1arke** [comment]
Closing since 7.9 is no longer supported, and this issue could not be replicated. Please raise a new issue if you can replicate this on the latest Sonarqube LTS
