### ISSUE TITLE
Current edition does not support branch feature

### ISSUE THREAD

**Issue by jaymie9019** [mc1arke/sonarqube-community-branch-plugin#287]
**Describe the bug**
I have installed this plugin, because my page can see the the multi branches, but once I scan my project use sonar.branch.name={branche_name}  paramter, scan will failed, it tell me Current edition does not support branch feature

it's my error json

{
  "task": {
    "id": "AXZG1LC73-GIFprHpKpq",
    "type": "REPORT",
    "componentId": "AXURbD-sm3c9unTAB3TJ",
    "componentKey": "open-platform",
    "componentName": "open-platform",
    "componentQualifier": "TRK",
    "status": "FAILED",
    "submittedAt": "2020-12-09T17:28:32+0800",
    "submitterLogin": "admin",
    "startedAt": "2020-12-09T17:28:33+0800",
    "executedAt": "2020-12-09T17:28:35+0800",
    "executionTimeMs": 1935,
    "logs": false,
    "errorMessage": "Current edition does not support branch feature",
    "hasScannerContext": true,
    "organization": "default-organization",
    "branch": "test",
    "branchType": "BRANCH",
    "warningCount": 0,
    "warnings": [
      
    ]
  }
}

**it's my env**
![image](https://user-images.githubusercontent.com/28673896/101613355-9f51ec00-3a46-11eb-94eb-51a02c149d22.png)

it's failed 
![image](https://user-images.githubusercontent.com/28673896/101613407-b09af880-3a46-11eb-9104-15bebc1e2702.png)

it's the message
![image](https://user-images.githubusercontent.com/28673896/101613430-b7297000-3a46-11eb-9bfc-5a87935d4598.png)

**Comment by nixel2007** [comment]
Have you copied plugins to **both** intallation directories?

**Comment by jaymie9019** [comment]
> Have you copied plugins into **both** intallation directories?

yup， put to extensions/plugins and  lib/common/

**Comment by jmecosta** [comment]
Same problem here:

```
2020.12.09 22:34:38 ERROR web[AXZJKhPoowW1qDEBAACM][o.s.s.w.WebServiceEngine] Fail to process request http://localhost:9000/api/ce/submit?projectKey=tekla.structures.core%3ACliper&projectName=Cliper&characteristic=branch%3Dfeature%2Fabc&characteristic=branchType%3DBRANCH
java.lang.IllegalStateException: Current edition does not support branch feature
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:60)
	at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:84)
	at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:113)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:88)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:80)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by jaymie9019** [comment]
> java.lang.IllegalStateException: Current edition does not support branch feature

I have solved, how about you

**Comment by eLpOnJA** [comment]
@jaymie9019 how do you do? I have the same problem, when I specified the branch name... I get this error.

Thanks in advance!

**Comment by gnomeria** [comment]
> > java.lang.IllegalStateException: Current edition does not support branch feature
> 
> I have solved, how about you

How did you solve it @jaymie9019 ?

**Comment by balusarakesh** [comment]
@jaymie9019 how did you solve the problem?

We are also seeing this issue
sonarqube version: `8.9.6-community`
community branch plugin version: `1.8.1`

 - Thank you

**Comment by danilooliveira88** [comment]
@jaymie9019 how did you solve the problem?
We are also seeing this issue
sonarqube version: 9.2.4-community
community branch plugin version: 1.10.0

The plugin JAR file is placed in both locations extensions/plugins and lib/common

Thank you

**Comment by mateuszgazdziak** [comment]
For me, I had to make it work:
- JAR is placed in `extensions/plugins` and `lib/common`.
- JAR has `744` permissions. I had dedicated user and group to run sonarqube.
