### ISSUE TITLE
[GitLab] Error when trying to decorate PR/MR on self-hosted GitLab

### ISSUE THREAD

**Issue by p3k** [mc1arke/sonarqube-community-branch-plugin#288]
**Describe the bug**

Apart from the three settings mentioned in the README it seems it is also necessary to define `sonar.pullrequest.gitlab.repositorySlug`with `$CI_MERGE_REQUEST_PROJECT_ID` in `.gitlab-ci.yml` – which I only found out by web searching the property name.

Here is the error message from the compute engine log:

```plain
2020.12.09 20:29:35 ERROR ce[AXZI-vCeste3nam8JjZp][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalStateException: sonar.pullrequest.gitlab.repositorySlug must be specified in the project configuration or as scanner parameter
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.UnifyConfiguration.lambda$getRequiredProperty$0(UnifyConfiguration.java:46)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.UnifyConfiguration.getRequiredProperty(UnifyConfiguration.java:45)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabServerPullRequestDecorator.decorateQualityGateStatus(GitlabServerPullRequestDecorator.java:98)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:139)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:113)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:107)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Software Versions**
 - SonarQube Version: 7.9.3.33349
 - Plugin Version: 1.3.2

**Comment by hankchan101** [comment]
-Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID

**Comment by p3k** [comment]
@hankchan101 what does this setting do? is it an alternative to the `repositorySlug` setting?

@mc1arke would be nice to get a reason for closing this issue… not interested in fixing the documentation?

**Comment by mc1arke** [comment]
@p3k as there weren't a high number of people providing reactions or a 'me too' on your issue, it doesn't seem like it's causing a lot of problems. This property is no longer required (or even supported) in versions of the plugin targeting the 8.X range of Sonarqube, so adding this to documentation in a place that people can easily find it is challenging, and this ticket provides enough detail should someone be searching the internet for the error message and not be able to understand what the error means.

**Comment by p3k** [comment]
thanks for the clarification @mc1arke 

is the `sonar.pullrequest.key` setting @hankchan commented without further explanation the up-to-date way to setup pr decoration in 8.x versions? or in what way is it related to this issue?
