### ISSUE TITLE
PR decoration not working (8.7.1)

### ISSUE THREAD

**Issue by sldubinsky** [mc1arke/sonarqube-community-branch-plugin#320]
log from ce.log
```
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] using pull request decorator com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabServerPullRequestDecorator
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] starting to analyze with com.github.mc1arke.sonarqube.plugin.ce.pullrequest.AnalysisDetails@1c359f4f
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.response.MergeRequest received
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Status url is: http://someserver/api/v4/projects/39/statuses/5d2b13a842586f2796e20cddb5714141985cc1ff 
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] PR commits url is: http://someserver/api/v4/projects/39/merge_requests/2/commits 
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] MR discussion url is: http://someserver/api/v4/projects/39/merge_requests/2/discussions 
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] User url is: http://someserver/api/v4/user 
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.response.User received
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Using user: sonar_scanner 
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] MR discussions received
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] MR discussions received
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][c.g.m.s.p.c.p.g.GitlabServerPullRequestDecorator] Discussions in MR:  
2021.03.27 18:13:05 ERROR ce[AXh0PuWQtH5ZHiaQgx0K][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.base/java.text.DecimalFormat.format(DecimalFormat.java:515)
	at java.base/java.text.Format.format(Format.java:158)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.AnalysisDetails.createAnalysisSummary(AnalysisDetails.java:207)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabServerPullRequestDecorator.decorateQualityGateStatus(GitlabServerPullRequestDecorator.java:171)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:160)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:118)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:109)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:235)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:217)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:162)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:137)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:89)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2021.03.27 18:13:05 INFO  ce[AXh0PuWQtH5ZHiaQgx0K][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=FAILED | time=172ms
2
```

**Comment by sldubinsky** [comment]
sorry, it was my error. Incorrect coverage settings.

But, anyway, good idea to check correct type to "coverage" in 207 line

**Comment by chly1103** [comment]
**Version：Sonarqube 8.7.1+sonarqube-community-branch-plugin-1.7.0-SNAPSHOT.jar**

mvn sonar:sonar -Dsonar.projectKey=*** -Dsonar.projectName=*** -Dsonar.projectVersion=master -Dsonar.ws.timeout=30  -Dsonar.login=[MASKED] -Dsonar.sourceEncoding=UTF-8  -Dsonar.java.binaries=target/classes -Dsonar.java.test.binaries=target/test-classes -Dsonar.java.surefire.report=target/surefire-reports -Dsonar.test.inclusions=**/*test*/** -Dsonar.exclusions=**/*test*/** --settings=./settings.xml -Dsonar.branch.name=master

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project ils-parent: Failed to upload report - An error has occurred. Please contact your administrator -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

### **Successful execution without parameter -Dsonar.branch.name=master**

**Comment by andreiChis70** [comment]
@sldubinsky what settings have you set for coverage? I assume you don't have tests and coverage and you set some default values somewhere.

**Comment by sldubinsky** [comment]
> @sldubinsky what settings have you set for coverage? I assume you don't have tests and coverage and you set some default values somewhere.

yep
