### ISSUE TITLE
java.lang.IllegalStateException: Current edition does not support branch feature

### ISSUE THREAD

**Issue by Sryther** [mc1arke/sonarqube-community-branch-plugin#321]
**Describe the bug**
I upgraded yesterday my SonarQube version to 8.8.

I'm using the 1.7.0 plugin version released yesterday. When I build my project and do `mvn test sonar:sonar` I got the exception `java.lang.IllegalStateException: Current edition does not support branch feature`.

```
java.lang.IllegalStateException: Current edition does not support branch feature
 at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
 at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:59)
 at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:82)
 at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:100)
 at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
 at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
 at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
 at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
 at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
 at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
 at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
 at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
 at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.base/java.lang.Thread.run(Unknown Source)
```

It was working with a SonarQube 7.9 and 1.3.2 plugin version.

**To Reproduce**
1. Place the plugin JAR in `lib/common` and `extensions/plugins` directories with the right permissions (sonarqube user) ;
2. Restart SonarQube ;
3. Run `mvn test sonar:sonar -Dsonar.host.url=https://XXXXX -Dsonar.login=e5d... -Dsonar.branch.name=bugfix/a-custom-name` ;
4. See error "Failed to upload report - An error has occurred. Please contact your administrator" ;
5. Go to SonarQube logs and the exception.

**Expected behavior**
Build and analyze the branch.

**Screenshots**

**Software Versions**
 - SonarQube Version: Version 8.8 (build 42792)
 - Plugin Version: 1.7.0

**Additional context**

EDIT: Thanks for this awesome plugin. I'm using it from months now.

**Comment by mc1arke** [comment]
I'm unable to replicate this when using the following versions:
* Sonarqube 8.8.0.42792
* sonarqube-community-branch-plugin 1.7.0
* Centos 8
* Open JDK 11 (Server)
* Open JDK 8 (Maven)
* Maven 3.5.4

I've also tested this on a Windows host and build machine with both Gradle and Maven without any issues.

**Comment by Sryther** [comment]
I'm using `docker-compose` to run SonarQube.
Even if I mounted a volume to put the plugin in `lib/common`, the container didn't have it. I tried with an other way by creating a volume then copying the plugin within the directory.
I think that was the problem. I'm sorry for that.
