### ISSUE TITLE
Unable to read plugin manifest from jar

### ISSUE THREAD

**Issue by igor-dmitriev** [mc1arke/sonarqube-community-branch-plugin#339]
**Describe the bug**
Sonarqube fails to start with 1.7.0 version of the plugin and Sonarqube 8.8.0.42792
it fails with an error:

```
2021.04.17 09:17:16 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.7.0.jar
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
	at org.sonar.server.plugins.ServerPluginInfo.create(ServerPluginInfo.java:37)
	at org.sonar.server.plugins.PluginJarLoader.lambda$getExternalPluginsMetadata$5(PluginJarLoader.java:206)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.sonar.server.plugins.PluginJarLoader.loadPluginsFromDir(PluginJarLoader.java:236)
	at org.sonar.server.plugins.PluginJarLoader.getExternalPluginsMetadata(PluginJarLoader.java:206)
	at org.sonar.server.plugins.PluginJarLoader.loadPlugins(PluginJarLoader.java:92)
	at org.sonar.server.plugins.ServerPluginManager.start(ServerPluginManager.java:64)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:111)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel2Container(PlatformImpl.java:179)
	at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:87)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1529)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1430)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1437)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1268)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
	... 37 common frames omitted
```

**To Reproduce**
1. Install Sonarqube 8.8.0.42792
2. Donwload the jar from https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.7.0/sonarqube-community-branch-plugin-1.7.0.jar
3. Put it to `extension/plugins`
4. Restart the sonar server
4. See the error I posted earlier

**Expected behavior**
Plugin shoud be installed successfully

**Software Versions**
 - SonarQube Version: 8.8.0.42792
 - Plugin Version: 1.7.0

**Comment by sh-rutvik** [comment]
Same issue. 

```
2021.04.19 08:50:07 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2021.04.19 08:50:08 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2021.04.19 08:50:08 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9001]
2021.04.19 08:50:09 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 8.8.0.42792 / 8ea4b78e406a28fece1dbce33ae74e87c26f59ed
2021.04.19 08:50:09 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://localhost/pqsonar?currentSchema=public
2021.04.19 08:50:10 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube/sonarqube-8.8
2021.04.19 08:50:10 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2021.04.19 08:50:11 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/sonarqube-8.8/extensions/plugins/sonarqube-community-branch-plugin-1.7.0.jar
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
	at org.sonar.server.plugins.ServerPluginInfo.create(ServerPluginInfo.java:37)
	at org.sonar.server.plugins.PluginJarLoader.lambda$getExternalPluginsMetadata$5(PluginJarLoader.java:206)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.sonar.server.plugins.PluginJarLoader.loadPluginsFromDir(PluginJarLoader.java:236)
	at org.sonar.server.plugins.PluginJarLoader.getExternalPluginsMetadata(PluginJarLoader.java:206)
	at org.sonar.server.plugins.PluginJarLoader.loadPlugins(PluginJarLoader.java:92)
	at org.sonar.server.plugins.ServerPluginManager.start(ServerPluginManager.java:64)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:111)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel2Container(PlatformImpl.java:179)
	at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:87)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1581)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1476)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1483)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1288)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1251)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:285)
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
	... 37 common frames omitted
2021.04.19 08:50:11 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2021.04.19 08:50:11 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process

```

**Comment by igor-dmitriev** [comment]
just verified, everything works fine with `8.7.1.42226`

**Comment by sh-rutvik** [comment]
For me issue is still there in the `8.7.1.42226` as well 

```
2021.04.20 05:11:58 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2021.04.20 05:11:58 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2021.04.20 05:11:59 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9001]
2021.04.20 05:12:00 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 8.7.1.42226 / bb9cf2bea57608dacfbab18185f1476371a2e0f8
2021.04.20 05:12:00 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://localhost/pqsonar_87?currentSchema=public
2021.04.20 05:12:02 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube/sonarqube-8.7
2021.04.20 05:12:02 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2021.04.20 05:12:02 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/sonarqube-8.7/extensions/plugins/sonarqube-community-branch-plugin-1.7.0.jar
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
	at org.sonar.server.plugins.ServerPluginInfo.create(ServerPluginInfo.java:37)
	at org.sonar.server.plugins.PluginJarLoader.lambda$getExternalPluginsMetadata$5(PluginJarLoader.java:206)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.sonar.server.plugins.PluginJarLoader.loadPluginsFromDir(PluginJarLoader.java:236)
	at org.sonar.server.plugins.PluginJarLoader.getExternalPluginsMetadata(PluginJarLoader.java:206)
	at org.sonar.server.plugins.PluginJarLoader.loadPlugins(PluginJarLoader.java:92)
	at org.sonar.server.plugins.ServerPluginManager.start(ServerPluginManager.java:64)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:111)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel2Container(PlatformImpl.java:179)
	at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:87)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1581)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1476)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1483)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1288)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1251)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:285)
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
	... 37 common frames omitted
2021.04.20 05:12:02 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2021.04.20 05:12:02 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
```

**Comment by Rakdos8** [comment]
The installation guide says to put the plugin in `extensions/plugins` **and** `lib/common`. Did you put it there as well ?

**Comment by sh-rutvik** [comment]
@Rakdos8 Yes, it's in both directories

**Comment by Rakdos8** [comment]
Well, then I would say that the jar is corrupted on the download ? Here is my md5sum and sha1sum if it can help :
```txt
$ md5sum sonarqube-community-branch-plugin-1.7.0.jar
shaa639330db6ebbdc9f8701e4193773011  sonarqube-community-branch-plugin-1.7.0.jar
$ sha1sum sonarqube-community-branch-plugin-1.7.0.jar
f71831bb15ae1002c9b7a5bb973b46d7bea60885  sonarqube-community-branch-plugin-1.7.0.jar
```

**Comment by mc1arke** [comment]
All the releases of the plugin have worked fine for me against their targeted versions of Sonarqube, so this does sound like what @Rakdos8 has suggested where your plugin file has become corrupted. @sh-rutvik  Could you provide your checksums so we can confirm please?

**Comment by mc1arke** [comment]
Closing as unable to replicate and no follow-up from reporter.
