### ISSUE TITLE
BitbucketException: The field 'link' must be a valid HTTP or HTTPS URL

### ISSUE THREAD

**Issue by MarkusSchoelzel** [mc1arke/sonarqube-community-branch-plugin#357]
**Describe the bug**

After upgrading from 7.9 LTS to 8.9 LTS the following happens:

```
2021.05.17 11:07:10 ERROR ce[AXl6AhAxAzQ0OkQ5FQ1X][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketException: The field 'link' must be a valid HTTP or HTTPS URL
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketServerClient.validate(BitbucketServerClient.java:207)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.client.BitbucketServerClient.uploadReport(BitbucketServerClient.java:135)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.bitbucket.BitbucketPullRequestDecorator.decorateQualityGateStatus(BitbucketPullRequestDecorator.java:91)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:160)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:118)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:109)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021.05.17 11:07:10 INFO  ce[AXl6AhAxAzQ0OkQ5FQ1X][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=FAILED | time=682ms
```

ALM Integrations (Bitbucket):
Pull Request Decoration [green] Import repositories from your ALM [green]
[green] Configuration valid

There might be a problem in the database (postgresql 12.7)?

**To Reproduce**
1. Upgrade SonarQube from 7.9 LTS to 8.9 LTS (using .zip or docker)
2. Add Bitbucket Server /admin/settings?category=almintegration
3. Update /project/settings?category=pull_request_decoration_binding
4. See /api/system/logs?process=ce (and no integration in Bitbucket)

**Expected behavior**
Working Pull Request Decoration after upgrading SonarQube and sonarqube-community-branch-plugin

**Software Versions**
 - SonarQube Version: 8.9.0.43852
 - Plugin Version: 1.8.0
 - Bitbucket (Server Edition) Version: v7.6.5

**Comment by mc1arke** [comment]
Do you have your Sonarqube server's URL set properly in your server configuration (`sonar.core.serverBaseURL`)? If this has localhost in it then Bitbucket will request the request to create the report.

**Comment by MarkusSchoelzel** [comment]
Thanks for your reply!

sonar.core.serverBaseURL is set to https://sonarqube._redacted_.com via sonar.properties (and correctly shown in /admin/settings)

**Comment by rpo-fr** [comment]
hi,

i have a  problem similaire with plugin 1.8 and sonar 8.9.0: it use http instead of https
i check sonar.core.serverBaseURL and is set to https

2021.05.19 10:20:05 ERROR web[AXmEIlyOUYd719b5AABM][o.s.s.w.WebServiceEngine] Fail to process request http://sonar.<MY-DOMAIN>/api/alm_settings/validate?key=bitbucket%20server
java.lang.NullPointerException: null
	at java.base/java.util.Arrays.stream(Unknown Source)
	at java.base/java.util.stream.Stream.of(Unknown Source)
	at org.sonar.alm.client.bitbucketserver.BitbucketServerRestClient.getErrorMessage(BitbucketServerRestClient.java:170)
	at org.sonar.alm.client.bitbucketserver.BitbucketServerRestClient.handleError(BitbucketServerRestClient.java:151)
	at org.sonar.alm.client.bitbucketserver.BitbucketServerRestClient.doCall(BitbucketServerRestClient.java:138)
	at org.sonar.alm.client.bitbucketserver.BitbucketServerRestClient.doGet(BitbucketServerRestClient.java:120)
	at org.sonar.alm.client.bitbucketserver.BitbucketServerRestClient.validateUrl(BitbucketServerRestClient.java:71)
	at org.sonar.server.almsettings.ws.ValidateAction.validateBitbucketServer(ValidateAction.java:147)

**Comment by MarkusSchoelzel** [comment]
After fiddling with the link URL, I came to the conclusion, that 
[https://javadocs.sonarsource.org/8.9.0.43852/org/sonar/api/platform/Server.html#getPublicRootUrl()](https://javadocs.sonarsource.org/8.9.0.43852/org/sonar/api/platform/Server.html#getPublicRootUrl()) (used in PullRequestPostAnalysisTask.java) returned the correct URL, but without protocol.

I can't reproduce how the change occurred in the database, nor why it wasn't overridden by a change in the web interface or sonar.properties, but it works now, with a clean database, and I really appreciate your work and the cleanliness of your code.
