### ISSUE TITLE
Can't pr scan with brach which is not a main branch

### ISSUE THREAD

**Issue by jiangsuen** [mc1arke/sonarqube-community-branch-plugin#364]
**Describe the bug**
Can't pr scan with brach which is not a main branch.
Now the main branch is master in my sonar project, and I also have another brach develop.
After create a pr which is merge to develop branch in github, and it will trigger to pr scan in sonarqube.
But it will pr scan failed.
The error message is:  java.lang.IllegalStateException: Could not find target branch 'null' in project.
And if i create a pr which is merge to master branch, the pr scan can success.

**To Reproduce**
1. Install and config sonarqube-commmunity-branch-plugin, 
2. Create a jenkins job and add "Execute SonarQube Scanner" in configuration
![image](https://user-images.githubusercontent.com/52435009/119786573-ebb0bb80-bf02-11eb-80d1-ec42afae8fd3.png)

3. Create a pr which merge to develop branch. and it will auto trigger jenkins to build job. and the job building will auto trigger to scan pr.
Request command is:
```
Sonar_Scanner/bin/sonar-scanner -X -Dsonar.host.url=http://10.xxx.xxx.xx:xxxx -Dsonar.sourceEncoding=UTF-8 -Dsonar.sources=./ -Dsonar.pullrequest.key=868 -Dsonar.language=py -Dsonar.exclusions=**/*.java,**/*.xml,**/*.jar,**/*.txt,**/*.ini -Dsonar.pullrequest.branch=for_test_sonarpr -Dsonar.projectVersion=1.0 -Dsonar.projectKey=sonarqube: test_pullrequest_commitbuilding -Dsonar.pullrequest.base=develop -Dsonar.projectName=test_pullrequest_commitbuilding -Dsonar.projectBaseDir=/home1/deploy/test_pullrequest_commitbuilding
```
4. Check pr scan result in sonar

**Expected behavior**
1. Develop branch will created in sonar project.
2. The pr scan will executed under the develop branch successfully.
3. Can get pr scan result successfully.

**Actual Result**
1. There is only master branch, there is no develop branch in sonar project.
2. PR scan failed, and there are an error message and an alarm in sonar:
3. 
```
java.lang.IllegalStateException: Could not find target branch 'null' in project
	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.createPullRequest(CommunityBranchLoaderDelegate.java:98)
	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.load(CommunityBranchLoaderDelegate.java:78)
	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.load(CommunityBranchLoaderDelegate.java:50)
	at org.sonar.ce.task.projectanalysis.component.BranchLoader.load(BranchLoader.java:44)
	at org.sonar.ce.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.execute(LoadReportAnalysisMetadataHolderStep.java:90)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:235)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:217)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:162)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:137)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:89)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
![image](https://user-images.githubusercontent.com/52435009/119789944-15b7ad00-bf06-11eb-9ded-6f25252f5860.png)

**Software Versions**
 - SonarQube Version: Community Edition  8.5.1 (build 38104)
 - Plugin Version: 1.6.0

**Additional context**
We try to modify the main branch name to "develop" and  retry again. and the pr scan can executed successfully.
But I think it is not a good solution for developer, because the sonar project always can have only 1 branch, can't get more branch.

**Comment by mc1arke** [comment]
Your target branch for your PR (`develop` in your example) needs to have been scanned as a branch prior to submitting a PR/MR against that target branch.

**Comment by jiangsuen** [comment]
@mc1arke Thanks.
I tried to branch scan for develop branch just now.
And develop branch is created in sonar.
![image](https://user-images.githubusercontent.com/52435009/119792940-b7d89480-bf08-11eb-8585-2fab0a0a5e03.png)

And I tried to pr scan (please refer "To Reproduce" in issue), and found the pr result is wrong and there is an alarm for the pr scan.
![image](https://user-images.githubusercontent.com/52435009/119794537-31bd4d80-bf0a-11eb-9bec-1aaa751247c3.png)
![image](https://user-images.githubusercontent.com/52435009/119795878-75fd1d80-bf0b-11eb-9b4e-cc5f34a247ee.png)

PR scan's alarm:
![image](https://user-images.githubusercontent.com/52435009/119789944-15b7ad00-bf06-11eb-9ded-6f25252f5860.png)

So..there seems to be some problems.
How do I resolve it?

**Comment by mc1arke** [comment]
The warning is saying that the `develop` branch isn't recognised in your Git refs, did you checkout that branch as part of your Pull Request job? For your incorrect results: have you purposefully introduced problems into your branch to prove these issues? The results of a PR scan only show the new issues introduced in that PR, not all existing issues, Have you also checked the run logs to ensure items like code coverage measures are being applied?

**Comment by jiangsuen** [comment]
@mc1arke 
Yes, develop branch had been checkout, before create pr,
![image](https://user-images.githubusercontent.com/52435009/119810119-53bdcc80-bf18-11eb-9fee-2ac11ba65aff.png)

And I added wrong codes, but the pr scan can't catch the wrong code's error. 
![image](https://user-images.githubusercontent.com/52435009/119810235-6f28d780-bf18-11eb-9d3f-1731a9609ed5.png)
![image](https://user-images.githubusercontent.com/52435009/119810450-a1d2d000-bf18-11eb-92d9-7f557e662e30.png)

Why i can't get correct pr scan result？what's the problem？

**Comment by mc1arke** [comment]
@jiangsuen you've not provided enough detail to allow this to be replicated. Analysis and decoration works for the various test cases I use, so the plugin can do this properly. I therefore need a minimum set of steps - ideally in a repository I can clone and execute a set of basic commands against.

**Comment by mc1arke** [comment]
Closing due to no recent updates, and lack of replication steps.
