### ISSUE TITLE
Error during SonarScanner execution

### ISSUE THREAD

**Issue by jaysson1710** [mc1arke/sonarqube-community-branch-plugin#365]
i'm using this plugin, but threw this error:

```
##[error]00:14:55.475 ERROR: Error during SonarScanner execution
##[debug]Processed: ##vso[task.logissue type=error;]00:14:55.475 ERROR: Error during SonarScanner execution
00:14:55.475 ERROR: Error during SonarScanner execution
##[error]Failed to upload report - An error has occurred. Please contact your administrator
##[debug]Processed: ##vso[task.logissue type=error;]Failed to upload report - An error has occurred. Please contact your administrator
Failed to upload report - An error has occurred. Please contact your administrator
##[debug]Exit code 2 received from tool '/azp/agent/_work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/4.20.0/sonar-scanner/bin/sonar-scanner'
##[debug]STDIO streams have closed for tool '/azp/agent/_work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/4.20.0/sonar-scanner/bin/sonar-scanner'
##[debug]task result: Failed
##[error]The process '/azp/agent/_work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/4.20.0/sonar-scanner/bin/sonar-scanner' failed with exit code 2
##[debug]Processed: ##vso[task.issue type=error;]The process '/azp/agent/_work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/4.20.0/sonar-scanner/bin/sonar-scanner' failed with exit code 2
##[debug]Processed: ##vso[task.complete result=Failed;]The process '/azp/agent/_work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/4.20.0/sonar-scanner/bin/sonar-scanner' failed with exit code 2
Finishing: Run Code Analysis
```

I have tried with different combinations:
- setting sonar.branch.name
- changing project name

**Comment by mc1arke** [comment]
This doesn't contain enough detail to work with:
* What version of Sonarqube and the plugin do you have installed?
* What do the Sonarqube Web logs say?
* What parameters are you passing to your build tool?
* Did this work before you installed the plugin?

**Comment by jaysson1710** [comment]
- version SonarQube 8.6
- plugin version 1.6
- parameters:
  sonar.sources=src
  sonar.sourceEncoding=UTF-8
  sonar.exclusions=$(exclusions)
- yes, the project works without plugin

**Comment by mc1arke** [comment]
I still need to know what the Sonarqube logs say, probably the web logs given the error you're having.

**Comment by bNobo** [comment]
Hi, I have the same error, in *logs/web.log* the error is:

```log
2021.06.09 09:52:10 ERROR web[AXnvvxAGweCC3UhCAAwt][o.s.s.w.WebServiceEngine] Fail to process request http://secibsonarqube.francecentral.cloudapp.azure.com/api/ce/submit?projectKey=Next&projectName=Next&characteristic=pullRequest%3D3041
java.lang.IllegalStateException: Current edition does not support branch feature
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:59)
        at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:82)
        at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:100)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
        at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
        at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
        at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
I have copied .jar file in *extensions/plugins* and modified *sonar.web.javaAdditionalOptions* and *sonar.ce.javaAdditionalOptions* in *conf/sonar.properties* according to README.md.

The plugin appears to be "installed" in the market place but it doesn't seem to work.

I'm using a preinstalled bitnami VM. It was working well with version 7.9.6 LTS. It does not work anymore since I upgraded to 8.9 LTS.

**Comment by mc1arke** [comment]
Can you provide the startup logs for the web and CE components please? I suspect CE hasn't picked up the plugin which wouldn't be visible from the front-end since it's only looking at Web when listing plugins, and potentially indicates that your startup parameters aren't quite right.

**Comment by bNobo** [comment]
In *sonar.properties* I set

```properties
sonar.web.javaAdditionalOpts=-server -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=web

sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=ce
```

*web.log*:

```log
2021.06.09 15:28:17 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2021.06.09 15:28:17 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2021.06.09 15:28:18 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9200]
2021.06.09 15:28:19 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 8.9.0.43852 / 681d1975f698b70fc4e981593f7bed298ff2f60d
2021.06.09 15:28:19 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:sqlserver://my.database.windows.net:1433;database=db-sonarqube;user=sonarqube;password=mypassword;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
2021.06.09 15:28:21 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/bitnami/apps/sonarqube/sonarqube
2021.06.09 15:28:21 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin C# Code Quality and Security / 8.22.0.31243 / e3cee7838d992e31dcdd90cf4f7406bb20535e8e
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin CSS Code Quality and Security / 1.4.2.2002 / faa7d4f1407df67df7ada53caf677ab783721173
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Community Branch Plugin / 1.8.0 / null
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Flex Code Quality and Security / 2.6.1.2564 / bb723840701bda72510b7a47742811d20daad331
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Go Code Quality and Security / 1.8.3.2219 / d6ad7a5a47fc4785d2e80918fb7424be46e38a7f
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin HTML Code Quality and Security / 3.4.0.2754 / 38f7ff864ae15152c9f1efc3014594f7e7ca7b6e
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin JaCoCo / 1.1.1.1157 / 83478572b9f23efac29de15e30c7758bbb0c0e47
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Java Code Quality and Security / 6.15.1.26025 / 1b1e96715bfa9f6a4ae24e95cc5b91f0edce609f
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin JavaScript/TypeScript Code Quality and Security / 7.4.3.15529 / 98601129c049a67155ee0af7dacad512f1eb67c7
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Kotlin Code Quality and Security / 1.8.3.2219 / d6ad7a5a47fc4785d2e80918fb7424be46e38a7f
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin PHP Code Quality and Security / 3.17.0.7439 / 44c7760147080c157fa0ff579772f92d3c8e1ebf
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Python Code Quality and Security / 3.4.1.8066 / 22139ec73fb2f32044f66477ea52734415683668
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Ruby Code Quality and Security / 1.8.3.2219 / d6ad7a5a47fc4785d2e80918fb7424be46e38a7f
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Scala Code Quality and Security / 1.8.3.2219 / d6ad7a5a47fc4785d2e80918fb7424be46e38a7f
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin VB.NET Code Quality and Security / 8.22.0.31243 / e3cee7838d992e31dcdd90cf4f7406bb20535e8e
2021.06.09 15:28:22 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin XML Code Quality and Security / 2.2.0.2973 / 16002945f0725643a7b42f090572795dd8b72a0f
2021.06.09 15:28:23 INFO  web[][o.s.s.p.d.m.c.MssqlCharsetHandler] Verify that database collation is case-sensitive and accent-sensitive
2021.06.09 15:28:23 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.platform.web.WebServiceFilter@4d60a1fd [pattern=UrlPattern{inclusions=[/api/system/migrate_db.*, ...], exclusions=[/api/components/update_key, ...]}]
2021.06.09 15:28:23 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2021.06.09 15:28:25 INFO  web[][o.s.s.p.UpdateCenterClient] Update center: https://update.sonarsource.org/update-center.properties (no proxy)
2021.06.09 15:28:28 INFO  web[][o.s.s.s.LogServerId] Server ID: 836E391F-AWuC4s1YxKLLe88Sz62d
2021.06.09 15:28:28 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/plugins/download
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/permissions/search_templates
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/list_bitbucketserver_projects
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/check_pat
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/list_azure_projects
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/search_bitbucketserver_repos
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/search_azure_repos
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/list_github_organizations
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/list_github_repositories
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/get_github_client_id
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_settings/get_binding
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_settings/list
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_settings/list_definitions
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_settings/count_binding
2021.06.09 15:28:29 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_settings/validate
2021.06.09 15:28:29 INFO  web[][o.s.s.t.TelemetryDaemon] Sharing of SonarQube statistics is enabled.
2021.06.09 15:28:29 INFO  web[][o.s.s.n.NotificationDaemon] Notification service started (delay 60 sec.)
2021.06.09 15:28:29 INFO  web[][o.s.s.s.GeneratePluginIndex] Generate scanner plugin index
2021.06.09 15:28:29 INFO  web[][o.s.s.s.RegisterPlugins] Register plugins
2021.06.09 15:28:29 INFO  web[][o.s.s.a.p.ExpiredSessionsCleaner] Purge of expired session tokens has removed 0 elements
2021.06.09 15:28:29 INFO  web[][o.s.s.a.p.ExpiredSessionsCleaner] Purge of expired SAML message ids has removed 0 elements
2021.06.09 15:28:29 INFO  web[][o.s.s.s.RegisterMetrics] Register metrics
2021.06.09 15:28:31 INFO  web[][o.s.s.r.RegisterRules] Register rules
2021.06.09 15:30:01 INFO  web[][o.s.s.q.BuiltInQProfileRepositoryImpl] Load quality profiles
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register quality profiles
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile css/Sonar way
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile scala/Sonar way
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile jsp/Sonar way
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile go/Sonar way
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile kotlin/Sonar way
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile js/Sonar way
2021.06.09 15:30:02 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile py/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile ruby/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile cs/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile java/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile web/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile flex/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile xml/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile php/Sonar way
2021.06.09 15:30:03 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile php/PSR-2
2021.06.09 15:30:04 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile php/Drupal
2021.06.09 15:30:04 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile vbnet/Sonar way
2021.06.09 15:30:04 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile ts/Sonar way
2021.06.09 15:30:04 INFO  web[][o.s.s.s.RegisterPermissionTemplates] Register permission templates
2021.06.09 15:30:04 INFO  web[][o.s.s.s.RenameDeprecatedPropertyKeys] Rename deprecated property keys
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.platform.web.SonarLintConnectionFilter@516672b2 [pattern=UrlPattern{inclusions=[/api/*], exclusions=[]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.platform.web.WebServiceFilter@19405cba [pattern=UrlPattern{inclusions=[/api/issues/delete_comment.*, ...], exclusions=[/api/authentication/login.*, ...]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.platform.web.WebServiceReroutingFilter@18574bfc [pattern=UrlPattern{inclusions=[/api/components/bulk_update_key, ...], exclusions=[]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.plugins.PluginsRiskConsentFilter@9700238 [pattern=UrlPattern{inclusions=[/*], exclusions=[*.css, ...]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.DefaultAdminCredentialsVerifierFilter@3e50e5bc [pattern=UrlPattern{inclusions=[/*], exclusions=[*.css, ...]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.InitFilter@7a6e7382 [pattern=UrlPattern{inclusions=[/sessions/init/*], exclusions=[]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.OAuth2CallbackFilter@40daf215 [pattern=UrlPattern{inclusions=[/oauth2/callback/*], exclusions=[]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ResetPasswordFilter@55c897ff [pattern=UrlPattern{inclusions=[/*], exclusions=[*.css, ...]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.LoginAction@77ad3346 [pattern=UrlPattern{inclusions=[/api/authentication/login], exclusions=[]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.LogoutAction@2cfee6c4 [pattern=UrlPattern{inclusions=[/api/authentication/logout], exclusions=[]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.ValidateAction@67aa9434 [pattern=UrlPattern{inclusions=[/api/authentication/validate], exclusions=[]}]
2021.06.09 15:30:05 INFO  web[][o.s.s.q.ProjectsInWarningDaemon] Counting number of projects in warning is not started as there are no projects in this situation.
2021.06.09 15:30:05 INFO  web[][o.s.s.p.p.PlatformLevelStartup] Running Community Edition
2021.06.09 15:30:05 INFO  web[][o.s.s.p.Platform] WebServer is operational
```

*ce.log*

``` log
2021.06.09 15:30:06 INFO  ce[][o.s.p.ProcessEntryPoint] Starting ce
2021.06.09 15:30:06 INFO  ce[][o.s.ce.app.CeServer] Compute Engine starting up...
2021.06.09 15:30:06 INFO  ce[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9200]
2021.06.09 15:30:07 INFO  ce[][o.sonar.db.Database] Create JDBC data source for jdbc:sqlserver://my.database.windows.net:1433;database=db-sonarqube;user=sonarqube;password=mypassword;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
2021.06.09 15:30:10 INFO  ce[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/bitnami/apps/sonarqube/sonarqube
2021.06.09 15:30:11 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
2021.06.09 15:30:12 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
2021.06.09 15:30:13 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is operational
```

**Comment by bNobo** [comment]
I just realized I didn't set access rights on the .jar file:

```bash
$ ls -hal sonarqube-community-branch-plugin-1.8.0.jar
-rw-r--r-- 1 root root      7.3M May 13 21:18 sonarqube-community-branch-plugin-1.8.0.jar
```

after updating:

```bash
$ sudo chmod 775 sonarqube-community-branch-plugin-1.8.0.jar
$ sudo chown root:sonarqube sonarqube-community-branch-plugin-1.8.0.jar
$ ls -hal sonarqube-community-branch-plugin-1.8.0.jar
-rwxrwxr-x 1 root sonarqube 7.3M May 13 21:18 sonarqube-community-branch-plugin-1.8.0.jar
```

and `sudo reboot`, it is now working like a charm.
