### ISSUE TITLE
plugin failing to load sonarqube 9.0-SNAPSHOT

### ISSUE THREAD

**Issue by michalliu** [mc1arke/sonarqube-community-branch-plugin#371]
```
jvm 1    | 15:47:10.573 [main] INFO com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Loading agent
jvm 1    | 15:47:10.577 [main] DEBUG com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Transforming class org.sonar.server.almsettings.MultipleAlmFeatureProvider
jvm 1    | 2021.06.18 15:47:15 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
jvm 1    | 2021.06.18 15:47:16 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
jvm 1    | 2021.06.18 15:47:16 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
jvm 1    | 2021.06.18 15:47:16 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

contents from **web.log**
```
021.06.18 15:47:15 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/search_azure_repos
2021.06.18 15:47:15 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/list_github_organizations
2021.06.18 15:47:15 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/list_github_repositories
2021.06.18 15:47:15 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/alm_integrations/get_github_client_id
2021.06.18 15:47:15 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: The action 'create_bitbucketcloud' is defined multiple times in the web service 'api/alm_settings'
	at org.sonar.api.server.ws.WebService$NewController.createAction(WebService.java:176)
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.CreateAction.define(CreateAction.java:44)
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.action.CreateAction.define(CreateAction.java:29)
	at org.sonar.server.almsettings.ws.AlmSettingsWs.lambda$define$0(AlmSettingsWs.java:38)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.sonar.server.almsettings.ws.AlmSettingsWs.define(AlmSettingsWs.java:38)
	at org.sonar.server.ws.WebServiceEngine.start(WebServiceEngine.java:76)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:581)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:187)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021.06.18 15:47:15 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
```

**Comment by mc1arke** [comment]
This is expected. Sonarqube 9.0 adds the webservice definitions for Bitbucket cloud definition which this plugin has previously provided, so detects a clash. This fix is fairly simple, but I'm waiting to see what else changes in Sonarqube before fixing this.

**Comment by michalliu** [comment]
> This is expected. Sonarqube 9.0 adds the webservice definitions for Bitbucket cloud definition which this plugin has previously provided, so detects a clash. This fix is fairly simple, but I'm waiting to see what else changes in Sonarqube before fixing this.

ok，I just rename **create_bitbucketcloud** to **plugin_create_bitbucketcloud** the plugin loaded successful, but it seems plugin doesn't work. The scanning command executed successfully, but there is no result on web interface.

**Comment by michalliu** [comment]
downgrade sonarqube to 8.9.2 with the plugin works perfectly, thank you.
