### ISSUE TITLE
plugin is ineffective in 7.9.6

### ISSUE THREAD

**Issue by heidricha** [mc1arke/sonarqube-community-branch-plugin#381]
**Describe the bug**
plugin loaded, but still ineffective after upgrading to 7.9.6

**To Reproduce**
Go to any project page
There's no branches may more, only master
OR 
Go Administratiorn/configuration
There're no branch settings, like pattern for long lived branches

**Expected behavior**

**Screenshots**

**Software Versions**
 - SonarQube Version: [e.g. Version

7.9.6.41879
--
 - Plugin Version: [e.g. 1.1.0, or custom build from master at commit 004AD34FAA]
1.3.1 and 1.3.2

**Additional context**
startup log:
```
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:04 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:05 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:05 INFO  web[][o.e.p.PluginsService] no modules loaded
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:05 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:05 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:05 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:06 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:06 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 7.9.6.41879 / 38d385dda4435530bb4fdf77e0d28e31c401a976
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:06 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://postgres/sonar-7-5
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:07 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:07 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Build Breaker / 2.3.1.347
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin C++ (Community) / 2.0.3.2771 / c83dbfeb599c4f3d847c54b4b441e714c2ed71ee
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Cobertura / 2.0 / 0846f534a418ec3871147c0e3f2aad1561d9747c
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Community Branch Plugin / 1.3.1
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin GitLab / 4.1.0-SNAPSHOT / 0
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Issue resolver / 1.0.2
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin JaCoCo / 1.1.0.898 / f65b288e6c2888393bd7fb72ad7ac1425f88eebf
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Java Code Quality and Security / 6.3.2.22818 / 5bbf3112d1ac8287fd3681482f2502072d0e1a4f
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Mutation Analysis / 1.5
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJS / 6.2.2.13315 / 89eaee748b1c660c0d57ebac1fbdd3e4063713d8
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarPython / 2.8.0.6204 / 5600d1ed780882d2362bedb3604dbad7ea63eb27
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarTS / 2.1.0.4359 / 268ba9581b700c4fb2bc194d4069d283da915213
ESC[33msonar_1     |ESC[0m 2021.07.07 09:03:08 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Sonargraph Integration / 6.0.0
```

webserver log:
```
2021.07.07 02:07:27 ERROR web[AXp8SHXiMGQgRdtFAA3p][o.s.s.w.WebServiceEngine] Fail to process request http://sonar/api/ce/submit?projectKey=dc-web-ui&projectName=dc-web-ui&characteristic=branch%3Ddevelop&characteristic=branchType%3DLONG
java.lang.IllegalStateException: Current edition does not support branch feature
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:66)
	at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:83)
	at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:121)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
	at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:88)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
2021.07.07 02:24:51 ERROR web[AXp8SHXiMGQgRdtFAA5n][o.s.s.w.WebServiceEngine] Fail to process request http://sonar/api/ce/submit?projectKey=distrib-controller&characteristic=branch%3Ddevelop&characteristic=branchType%3DLONG
```

**Comment by mc1arke** [comment]
This looks like you don't have the plugin installed to both the directories mentioned in the README for that version. Can you confirm the files are there and accessible by the Sonarqube user. You also mention upgrading; did this work with a previous setup, and if so what were the version numbers?

**Comment by heidricha** [comment]
> This looks like you don't have the plugin installed to both the directories mentioned in the README for that version. Can you confirm the files are there and accessible by the Sonarqube user. You also mention upgrading; did this work with a previous setup, and if so what were the version numbers?

Bullseye!

Thanks a lot for the QUICK answer! Closing it now.
Sorry by the way, just checked the REDME in default branch, the 1_3 really contains the right method - and gives the solution as well. lib/common is not mounted volume for my docker, so got overwritten at upgrade (recreate)

Thanks again!
