### ISSUE TITLE
sonarqube9.0 Failed to upload report - An error has occurred. Please contact your administrator

### ISSUE THREAD

**Issue by dreamerkr** [mc1arke/sonarqube-community-branch-plugin#384]
**Describe the bug**
1. mvn clean package sonar:sonar -Dsonar.branch.name=master -Dmaven.test.skip=true

 a.、maven error log:
```
> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project devops: Failed to upload report - An error has occurred. Please contact your administrator -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

b. sonar web log:

```
> 2021.07.08 14:26:03 ERROR web[AXqEtCg1l3hmsPCeAADf][o.s.s.w.WebServiceEngine] Fail to process request http://127.0.0.1:9000/api/ce/submit?projectKey=com.shuyun.devops%3Adevops&projectName=devops&characteristic=branch%3Dmaster&characteristic=branchType%3DBRANCH
> java.lang.IllegalStateException: Current edition does not support branch feature
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
> 	at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:59)
> 	at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:82)
> 	at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:100)
> 	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:111)
> 	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
> 	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
> 	at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
> 	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
> 	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
> 	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
> 	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
> 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
> 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Software Versions**
 - SonarQube Version: 9.0
 - Plugin Version: 1.8
**Additional context**

**Comment by mc1arke** [comment]
The plugin does not currently support Sonarqube 9.0, so this is expected.

**Comment by dreamerkr** [comment]
> The plugin does not currently support Sonarqube 9.0, so this is expected.

thanks.  Plugin Version: 1.9.0 support Sonarqube 9.0? when 1.9.0  publish release

**Comment by rafaelmoridata** [comment]
I'm facing the same error but apparently supported version:
- SonarQube version by the console: Community EditionVersion 8.9 (build 43852) 
- Plugin version: 1.8.0
- Maven execution
- Sonarqube DB Postgresql

Jenkins error: 
- [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project m2mii: Failed to upload report - HTTP code 500 -> [Help 1]

SonarQube error:
- ==> web.log <==
2021.07.12 17:51:58 ERROR web[AXqN...][o.s.s.w.WebServiceEngine] Fail to process request http://sonarqubeurl/sonarqube/api/ce/submit?projectKey=pt.vdf%3Am2mii&projectName=M2MII&characteristic=branch%3Drelease%2FFD21.3&characteristic=branchType%3DBRANCH
java.lang.IllegalStateException: Current edition does not support branch feature

**Comment by mc1arke** [comment]
@rafaelmoridata your issue is unrelated to the Sonarqube update as you're own a version of the plugin that has been tested with the version of Sonarqube you're using. Your issue is likely to be a misconfiguration of Sonarqube so that it isn't loading the plugin properly. Please check the installation instructions for the version of the plugin you're using and ensure you've followed them properly.

**Comment by vsuryateja** [comment]
> I'm facing the same error but apparently supported version:
> 
> * SonarQube version by the console: Community EditionVersion 8.9 (build 43852)
> * Plugin version: 1.8.0
> * Maven execution
> * Sonarqube DB Postgresql
> * Running on docker instances
> 
> Jenkins error:
> 
> ```
>  [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project m2mii: Failed to upload report - HTTP code 500 -> [Help 1]
> ```
> 
> SonarQube error:
> 
> * ==> web.log <==
> 
> ```
> 2021.07.12 17:51:58 ERROR web[AXqN...][o.s.s.w.WebServiceEngine] Fail to process request http://sonarqubeurl/sonarqube/api/ce/submit?projectKey=pt.vdf%3Am2mii&projectName=M2MII&characteristic=branch%3Drelease%2FFD21.3&characteristic=branchType%3DBRANCH
> java.lang.IllegalStateException: Current edition does not support branch feature
> ```

any fix on this?

**Comment by mc1arke** [comment]
Release in v1.9.0 of the plugin

**Comment by BalajiGuruanywhere** [comment]
> @rafaelmoridata your issue is unrelated to the Sonarqube update as you're on a version of the plugin that has been tested with the version of Sonarqube you're using. Your issue is likely to be a misconfiguration of Sonarqube so that it isn't loading the plugin properly. Please check the installation instructions for the version of the plugin you're using and ensure you've followed them properly.

Hi, I am facing the same issue for 8.9.3, i tried everything, i configured it according to you instructions, made changes to conf/sonar.properties still dont know what to change.
