### ISSUE TITLE
[GitLab] Branch analysis are not supported

### ISSUE THREAD

**Issue by Rakdos8** [mc1arke/sonarqube-community-branch-plugin#407]
**Describe the bug**
The sonar analysis on `master` is OK but not on another branch.

**To Reproduce**
1. Create a random repository with default branch `master`
2. Create a new branch from `master` (eg `test`)
3. Commit a change to `test`
4. Run the sonar analysis on `test`

Here is the command line used : `sonar-scanner '-Dsonar.qualitygate.wait=true' '-Dsonar.login=****' '-Dsonar.branch.name=test' '-Dsonar.projectKey=prj_key' '-Dsonar.projectName=PRJ Name'`

**Expected behavior**
I was expecting that the branch analysis are working according to the README : https://github.com/mc1arke/sonarqube-community-branch-plugin#run-analysis-of-branches

**Screenshots**
Here is the log from SonarQube :
```txt
java.lang.IllegalStateException: Branches and Pull Requests are not supported in Community Edition
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at org.sonar.ce.task.projectanalysis.analysis.AnalysisMetadataHolderImpl.setBranch(AnalysisMetadataHolderImpl.java:141)
	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.load(CommunityBranchLoaderDelegate.java:52)
	at org.sonar.ce.task.projectanalysis.component.BranchLoader.load(BranchLoader.java:44)
	at org.sonar.ce.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.execute(LoadReportAnalysisMetadataHolderStep.java:74)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Software Versions**
 - SonarQube Version: 8.9.2 (build 46101)
 - Plugin Version: 1.8.0 download from the released page

**Additional context**
GitLab is used

**Comment by mc1arke** [comment]
`java.lang.IllegalStateException: Branches and Pull Requests are not supported in Community Edition` indicates you've not installed the plugin properly.

**Comment by Rakdos8** [comment]
Exactly. I copied/pasted the same line in the `config.properties`.
My bad.

It should be
```txt
sonar@kub-mlh-p01:~/sonarqube-8.9.2.46101$ cat conf/sonar.properties | grep "javaAdditionalOpts"
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=ce
#sonar.search.javaAdditionalOpts=
```
