### ISSUE TITLE
Github - cannot post summary comment

### ISSUE THREAD

**Issue by rock-tran** [mc1arke/sonarqube-community-branch-plugin#408]
**Describe the bug**
Sonarqube can't post summary comment to PR on Github.
Even I already enabled the required permissions:
- Checks : r&w
- Metadata : r
- Pull requests  : r&w
- Commit statuses : r

```
java.lang.IllegalStateException: Could not decorate Pull Request on Github
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:45)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:160)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:118)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:109)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: An error was returned in the response from the Github API:
- Error{message='Resource not accessible by integration', locations=[Location{line='1', column='12'}]}
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.v4.GraphqlCheckRunProvider.executeRequest(GraphqlCheckRunProvider.java:240)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.v4.GraphqlCheckRunProvider.postSummaryComment(GraphqlCheckRunProvider.java:221)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.v4.GraphqlCheckRunProvider.createCheckRun(GraphqlCheckRunProvider.java:172)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:43)
	... 21 common frames omitted
```

**Screenshots**
![Screenshot from 2021-08-09 16-26-29](https://user-images.githubusercontent.com/43530559/128685771-b42c663c-a1a0-4543-b756-ebc871b9afdf.png)

**Software Versions**
 - SonarQube Version: Version 8.9.2 (build 46101)
 - Plugin Version: 1.8

**Additional context**

**Comment by mc1arke** [comment]
Can you provide a bit more detail please:
1. Is this a self-hosted Github (if so: which version) or Github.com?
2. Is this MR for a forked repository or from the same repository?

**Comment by rock-tran** [comment]
@mc1arke 
1. We are using Github.com, within our organization.
2. No, this is our private repository, no forked.

**Comment by rock-tran** [comment]
@mc1arke 
![image](https://user-images.githubusercontent.com/43530559/128805633-e3fac6b0-cc96-42d5-85a3-defb5fe29755.png)

When I install the Github app into repository, it appears.
Does it lack some required permissions ?

**Comment by mc1arke** [comment]
You need write access to Pull Requests to post summary comments.
