### ISSUE TITLE
Devops PR Decoration - Not working for projects/repos which contain spaces

### ISSUE THREAD

**Issue by axylophon** [mc1arke/sonarqube-community-branch-plugin#461]
The Devops PR Decoration is not working for projects/repos which have spaces in the name.
It is also not possible to configure it within the SonarUI.
The character Ö should in this case not be the problem as another project without umlauts is also not working.

![404](https://user-images.githubusercontent.com/55131237/135224953-ce7a1aad-a0b8-4ca4-b818-4c828c3de732.JPG)

```
2021.09.28 08:43:24 ERROR ce[AXwrJJXMpA_JVSv-Mudr][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalStateException: An unexpected response code was returned from the Azure Devops API - Expected: 200, Got: 404
	at com.github.mc1arke.sonarqube.plugin.almclient.azuredevops.AzureDevopsRestClient.validateResponse(AzureDevopsRestClient.java:157)
	at com.github.mc1arke.sonarqube.plugin.almclient.azuredevops.AzureDevopsRestClient.execute(AzureDevopsRestClient.java:129)
	at com.github.mc1arke.sonarqube.plugin.almclient.azuredevops.AzureDevopsRestClient.retrievePullRequest(AzureDevopsRestClient.java:107)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.azuredevops.AzureDevOpsPullRequestDecorator.getPullRequest(AzureDevOpsPullRequestDecorator.java:98)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.azuredevops.AzureDevOpsPullRequestDecorator.getPullRequest(AzureDevOpsPullRequestDecorator.java:60)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.DiscussionAwarePullRequestDecorator.decorateQualityGateStatus(DiscussionAwarePullRequestDecorator.java:69)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:160)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:110)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:101)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

`2021.09.28 08:43:14 ERROR web[AXwrDReRoh7bqy5KAAMA][c.g.m.s.p.a.a.AzureDevopsRestClient] Azure Devops response status did not match expected value. Expected: 200\r\nHTTP/1.1 404 Not Found\r\n`

**Comment by axylophon** [comment]
Hi, i have built the plugin from the latest master commit - looks good on the first test - the PR decoration is back alive for our repositories 🥇

**Comment by hokiepokedad2** [comment]
Hello, we are using the latest docker tag for this image in Azure. Possible to get a new tag with this fix in? 🙏

**Comment by mc1arke** [comment]
Released in 1.10.0 of the plugin

**Comment by rdelcampog** [comment]
@mc1arke Can this be backported to a Sonarqube 8.9 compatible plugin version (v1.8.2)?

We have this problem but need to use the LTS version :(

**Comment by mattsteinRRD** [comment]
Same here.  We are using the LTS version of SonarQube :(
