### ISSUE TITLE
Gitlab Merge Request Decoration breaks for clean install of SonarQube 9.1

### ISSUE THREAD

**Issue by Lemmah** [mc1arke/sonarqube-community-branch-plugin#478]
**Describe the bug**
After a clean install of SonarQube 9.1, I did a manual install of the sonarqube-community-branch-plugin version 1.9.0 and configured Gitlab <> SonarQube DevOps Platform Integration which works since I have imported projects from Gitlab. However, when analysing pull requests, the pull request decoration fails with the following error:
```
2021.10.18 05:43:48 INFO  ce[AXyRtnKux0cPMK90dM-M][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Webhooks | globalWebhooks=0 | projectWebhooks=0 | status=SUCCESS | time=4ms
2021.10.18 05:43:48 INFO  ce[AXyRtnKux0cPMK90dM-M][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] using pull request decorator com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator
2021.10.18 05:43:48 INFO  ce[AXyRtnKux0cPMK90dM-M][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=FAILED | time=275ms
2021.10.18 05:43:48 ERROR ce[AXyRtnKux0cPMK90dM-M][o.s.c.t.s.ComputationStepExecutor] Execution of listener failed
java.lang.NoSuchMethodError: 'java.lang.String org.sonar.db.alm.setting.AlmSettingDto.getPersonalAccessToken()'
	at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.DefaultGitlabClientFactory.createClient(DefaultGitlabClientFactory.java:53)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator.createClient(GitlabMergeRequestDecorator.java:74)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator.createClient(GitlabMergeRequestDecorator.java:52)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.DiscussionAwarePullRequestDecorator.decorateQualityGateStatus(DiscussionAwarePullRequestDecorator.java:67)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:160)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:110)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:101)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021.10.18 05:43:49 INFO  ce[AXyRtnKux0cPMK90dM-M][o.s.c.t.CeWorkerImpl] Executed task | project=business-banking_xxx-identity-extention_AXyPg1WTx0cPMK90dM9H | type=REPORT | pullRequest=34 | id=AXyRtnKux0cPMK90dM-M | submitter=xxx-development-tools5658 | status=SUCCESS | time=3050ms
```

**To Reproduce**
1. Install SonarQube 9.1
2. Install sonarqube-community-branch-plugin 1.9.0
3. Configure DevOps Platform Integration with Gitlab
4. Import a project from Gitlab
5. Set up CI analysis for branch and Merge Requests
6. Open a Merge request
7. Decoration fails, see the error at `$SONARQUBE_INSTALLATION/logs/ce.log`

**Expected behavior**
Just expected to see Merge Request decoration on Gitlab.

**Screenshots**
N/a

**Software Versions**
 - SonarQube Version: 9.1
 - Plugin Version: 1.9.0

**Additional context**
CI runs on Jenkins, but that shouldn't be an issue anyways.

**Comment by Lemmah** [comment]
Thanks for the quick response and direction @axylophon! I have built the plugin from source and the error is fixed, I am getting another error now:
```
2021.10.18 06:47:42 INFO  ce[AXyR8MboeaHBIKkjN-F3][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Webhooks | globalWebhooks=0 | projectWebhooks=0 | status=SUCCESS | time=5ms
2021.10.18 06:47:42 INFO  ce[AXyR8MboeaHBIKkjN-F3][c.g.m.s.p.c.p.PullRequestPostAnalysisTask] using pull request decorator com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator
2021.10.18 06:47:43 ERROR ce[AXyR8MboeaHBIKkjN-F3][c.g.m.s.p.a.g.GitlabRestClient] Gitlab response status did not match expected value. Expected: 200\nHttpResponseProxy{HTTP/1.1 404 Not Found [Server: nginx/1.14.1, Date: Mon, 18 Oct 2021 05:47:43 GMT, Content-Type: application/json, Content-Length: 27, Connection: keep-alive, Cache-Control: no-cache, Vary: Origin, X-Request-Id: 01FJ8Z205RB5D3MZ04FSQCKAG9, X-Runtime: 0.066374] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 27,Chunked: false]}}\n{"message":"404 Not found"}
2021.10.18 06:47:43 ERROR ce[AXyR8MboeaHBIKkjN-F3][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalStateException: An unexpected response code was returned from the Gitlab API - Expected: 200, Got: 404
	at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.validateResponse(GitlabRestClient.java:233)
	at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.lambda$entity$5(GitlabRestClient.java:168)
	at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.entity(GitlabRestClient.java:177)
	at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.entity(GitlabRestClient.java:168)
	at com.github.mc1arke.sonarqube.plugin.almclient.gitlab.GitlabRestClient.getMergeRequest(GitlabRestClient.java:76)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator.getPullRequest(GitlabMergeRequestDecorator.java:94)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabMergeRequestDecorator.getPullRequest(GitlabMergeRequestDecorator.java:52)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.DiscussionAwarePullRequestDecorator.decorateQualityGateStatus(DiscussionAwarePullRequestDecorator.java:69)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:160)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:110)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:101)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021.10.18 06:47:43 INFO  ce[AXyR8MboeaHBIKkjN-F3][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Pull Request Decoration | status=FAILED | time=292ms
2021.10.18 06:47:43 INFO  ce[AXyR8MboeaHBIKkjN-F3][o.s.c.t.CeWorkerImpl] Executed task | project=business-banking_xxx-identity-extention_AXyPg1WTx0cPMK90dM9H | type=REPORT | pullRequest=34 | id=AXyR8MboeaHBIKkjN-F3 | submitter=xxx-development-tools5658 | status=SUCCESS | time=13585ms
```
What am I missing?
