### ISSUE TITLE
Branch analysis is not working for SonarQube 8.9.6

### ISSUE THREAD

**Issue by vbhvjari** [mc1arke/sonarqube-community-branch-plugin#529]
Hi,
We have recently upgraded SonarQube from 7.9.6 community edition to 8.9.6 community edition(followed SonarQube recommendations during version upgrade activity).
Along with this upgrade, we have upgraded branch plugin version from 1.3.2 to 1.8.1.

We have hosted SonarQube application on containerised platform (Kubernetes). 
In previous sonar system(7.9.6), branch analysis feature was working as expected with below configuration:

1) copy plugin jar to `/opt/sonarqube/extensions/plugins` directory
1) Ensure to copy plugin jar to "lib/common/"
`cp /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.3.2.jar /opt/sonarqube/lib/common/`

In SonarQube 8.9.6, directory structure `lib/common` doesn't exist since SonarQube bundled all plugin jars.
As suggested in wiki page of this plugin, have added below lines in sonar.properties configuration:

```
sonar.web.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.8.1.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.8.1.jar=ce
```

After making above changes, SonarQube service is getting started without any issues. Here, we have ensured that configuration we added in sonar.properties file is getting considered during sonar start.

```
2022.01.03 12:52:39 INFO  web[][o.s.s.p.ServerPluginManager] Deploy plugin Community Branch Plugin / 1.8.1 / null
2022.01.03 12:53:59 INFO  web[][o.s.s.i.i.AsyncIssueIndexingImpl] 3052 branch found in need of issue sync.
2022.01.03 12:54:16 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='ce', ipcIndex=3, logFilenamePrefix=ce]] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED -Xmx8G -Xms512m -XX:+HeapDumpOnOutOfMemoryError -javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.8.1.jar=ce -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-8.9.6.50800.jar:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.19.jar org.sonar.ce.app.CeServer /opt/sonarqube/temp/sq-process4096800927102422314properties
12:54:16.803 [main] INFO com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Loading agent
12:54:16.807 [main] DEBUG com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Transforming class org.sonar.core.platform.PlatformEditionProvider
2022.01.03 12:54:17 INFO  ce[][o.s.c.e.CoreExtensionsLoader] Loaded core extensions: Community Branch Plugin

```

We have found that branch analysis is not working after making above changes. Sonar scan job getting failed with below error:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project sonar8.9.5: Failed to upload report - An error has occurred. Please contact your administrator -> [Help 1] 
```

Sonar server level logs say that this feature is not supported in community edition:
```
2022.01.03 13:15:33 ERROR web[AX4gBhU9nlvTlLIGAAEz][o.s.s.w.WebServiceEngine] Fail to process request http://sonar-dev.devtools.in.here.com/api/ce/submit?projectKey=com.here.dot.maventest-1%3Asonar8.9.5&projectName=sonar8.9.5&characteristic=branch%3Dsonar8.9.6&characteristic=branchType%3DBRANCH
java.lang.IllegalStateException: Current edition does not support branch feature
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:59)
	at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:82)
	at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:100)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
	at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1651)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Please help us to resolve the issue.

**Comment by mc1arke** [comment]
Could you share your full sonar start-up log please? The snippet you've provided shows an entry for `CommunityBranchAgent` so is working properly for the `ce` component, but I'm unable to tell from this log whether the `web` component is executing the agent properly.

**Comment by vbhvjari** [comment]
We are using additional web and CE parameters in sonar.properties file. Previously I have used sonar.web.javaAdditionalOpts and sonar.ce.javaAdditionalOpts twice in sonar.properties file. After collating all changes in single parameter, issue is resolved.
