### ISSUE TITLE
SonarQube PublishQuality Gate results throws an exception "Could not find target branch 'null' in project" while creating Merge Pullrequest with new Branch 

### ISSUE THREAD

**Issue by hoalaxanh123** [mc1arke/sonarqube-community-branch-plugin#533]
**Describe the bug**
Can't run a scan if the target branch is not the main branch

**To Reproduce**
1. From master create a new branch A
2. Run scan on the new branch A
3. From branch A create branch A1
4. Create merge request with target branch is A and source branch is A1 (merge `A1` --> `A`)

**Expected behavior**
Sonar will scan my MR without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/25761262/149908082-c18da473-08a4-44e3-85eb-14f8b08e6d9b.png)

**Software Versions**
 - SonarQube Version: Community EditionVersion 8.9.2 (build 46101)
 - Plugin Version:  1.8.1
 - I'm using Gitlab

**Additional context**
If I change the target branch to `master` in the MR ( merge `A1`  into the `master`). It runs without any issues.
The code I'm using in Gitlab CI
```
  qa:review:
    stage: qa
    image:
      name: sonarsource/sonar-scanner-cli:latest
      entrypoint: [ "" ]
    only:
      - merge_requests
    variables:
      GIT_STRATEGY: clone
      GIT_DEPTH: 0 # Missing blame information for the following files, shallow clone
    script:
      # Sonarqube New Code is specified if Overview is not display
      - sonar-scanner -Dsonar.host.url=$SONARQUBE_SERVER -Dsonar.login=$SONAR_TOKEN
        -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
        -Dsonar.projectVersion=$BUILD_NUMBER.$CI_PIPELINE_ID
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID
        -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        -Dsonar.pullrequest.provider=GitlabSonar
      ```

**Comment by vanducvo** [comment]
I also have issue in 9.2.3-community with plugin version: 1.10.0
```
java.lang.IllegalStateException: Branch has not been set
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at org.sonar.ce.task.projectanalysis.analysis.AnalysisMetadataHolderImpl.getBranch(AnalysisMetadataHolderImpl.java:150)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.createBranch(PostProjectAnalysisTasksExecutor.java:203)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.createProjectAnalysis(PostProjectAnalysisTasksExecutor.java:166)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:99)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022.01.18 09:44:58 ERROR ce[AX5sk0ZdNPS_4xNYV2Ef][o.s.c.t.CeWorkerImpl] Failed to execute task AX5sk0ZdNPS_4xNYV2Ef
java.lang.IllegalStateException: Could not find target branch 'null' in project
	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.createPullRequest(CommunityBranchLoaderDelegate.java:98)
	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.load(CommunityBranchLoaderDelegate.java:78)
	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.load(CommunityBranchLoaderDelegate.java:50)
	at org.sonar.ce.task.projectanalysis.component.BranchLoader.load(BranchLoader.java:44)
	at org.sonar.ce.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.execute(LoadReportAnalysisMetadataHolderStep.java:74)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by hoalaxanh123** [comment]
> I also have issue in 9.2.3-community with plugin version: 1.10.0
> 
> ```
> java.lang.IllegalStateException: Branch has not been set
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
> 	at org.sonar.ce.task.projectanalysis.analysis.AnalysisMetadataHolderImpl.getBranch(AnalysisMetadataHolderImpl.java:150)
> 	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.createBranch(PostProjectAnalysisTasksExecutor.java:203)
> 	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.createProjectAnalysis(PostProjectAnalysisTasksExecutor.java:166)
> 	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:99)
> 	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
> 	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
> 	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
> 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> 2022.01.18 09:44:58 ERROR ce[AX5sk0ZdNPS_4xNYV2Ef][o.s.c.t.CeWorkerImpl] Failed to execute task AX5sk0ZdNPS_4xNYV2Ef
> java.lang.IllegalStateException: Could not find target branch 'null' in project
> 	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.createPullRequest(CommunityBranchLoaderDelegate.java:98)
> 	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.load(CommunityBranchLoaderDelegate.java:78)
> 	at com.github.mc1arke.sonarqube.plugin.ce.CommunityBranchLoaderDelegate.load(CommunityBranchLoaderDelegate.java:50)
> 	at org.sonar.ce.task.projectanalysis.component.BranchLoader.load(BranchLoader.java:44)
> 	at org.sonar.ce.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.execute(LoadReportAnalysisMetadataHolderStep.java:74)
> 	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
> 	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
> 	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
> 	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
> 	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
> 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ```

How about the previous version? Is it running well?

**Comment by vanducvo** [comment]
@hoalaxanh123 I use helm chart of sonarqube to deploy.so I can not try previous version cannot install this plugins.

**Comment by hoalaxanh123** [comment]
@mc1arke Please help me

**Comment by mc1arke** [comment]
Does your target branch exist in Sonarqube?

**Comment by hoalaxanh123** [comment]
![image](https://user-images.githubusercontent.com/25761262/150175550-00852e23-51a1-493a-9f4d-3097d019bd39.png)
![image](https://user-images.githubusercontent.com/25761262/150175691-68e6da91-89a7-4bc9-bdde-7d2f2c1cbf47.png)

**Comment by hoalaxanh123** [comment]
@mc1arke Can I solve my problem? Please ask me to do something that can solve my problem. I want to know where I went wrong so I can fix it.
Thank you very much.

**Comment by hoalaxanh123** [comment]
Thank for your help. My mistake.

**Comment by ddagsan** [comment]
@hoalaxanh123 What was the solution?

**Comment by mengyan9521** [comment]
@hoalaxanh123 

I met the same issue, could you tell me how do you solve this issue?

**Comment by mengyan9521** [comment]
Thank you for your answer. 

>  You have to scan your target branch first, not the merge request.

You mean to solve the problem, I can change like this:

**BEFORE**

`-Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME`

**AFTER**

`-Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME`

Is that right?

**Comment by mengyan9521** [comment]
> @hoalaxanh123
> 
> Thank you for your answer.
> 
> > You have to scan your target branch first, not the merge request.
> 
> You mean to solve the problem, I can change like this:
> 
> **BEFORE**
> 
> ```yaml
> -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
> -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
> ```
> 
> **AFTER**
> 
> ```yaml
> -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
> -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
> ```
> 
> Is that right?

@hoalaxanh123 

Sorry to mention you.

Actually I set like this, also met the  `"Could not find target branch 'null' in project"` issue

```yaml
      -Dsonar.pullrequest.base=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
      -Dsonar.pullrequest.branch=${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
```
maybe, scanning the target branch firstly is not the right way to solve this issue?

I am so appreciate you can help me.

**Comment by hoalaxanh123** [comment]
Ok did you check your target branch exists on the sonar qube?
![image](https://user-images.githubusercontent.com/25761262/162351129-24eb9327-1df4-4ea1-8cf0-46bd129d9ead.png)
![image](https://user-images.githubusercontent.com/25761262/162351192-85a6bb0d-664f-45d5-99da-a1931aac1e5b.png)

**Comment by hoalaxanh123** [comment]
> > @hoalaxanh123
> > Thank you for your answer.
> > > You have to scan your target branch first, not the merge request.
> > 
> > 
> > You mean to solve the problem, I can change like this:
> > **BEFORE**
> > ```yaml
> > -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
> > -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **AFTER**
> > ```yaml
> > -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
> > -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is that right?
> 
> @hoalaxanh123
> 
> Sorry to mention you.
> 
> Actually I set like this, also met the `"Could not find target branch 'null' in project"` issue
> 
> ```yaml
>       -Dsonar.pullrequest.base=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
>       -Dsonar.pullrequest.branch=${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
> ```
> 
> maybe, scanning the target branch firstly is not the right way to solve this issue?
> 
> I am so appreciate you can help me.

**Comment by mengyan9521** [comment]
> @[mengyan9521](https://github.com/mengyan9521)
> 
> Ok did you check your target branch exists on the sonar qube? ![image](https://user-images.githubusercontent.com/25761262/162351129-24eb9327-1df4-4ea1-8cf0-46bd129d9ead.png) ![image](https://user-images.githubusercontent.com/25761262/162351192-85a6bb0d-664f-45d5-99da-a1931aac1e5b.png)

@hoalaxanh123 

OMG, You are right, I do not have the target branch in my SonarQube server.

So I have to scan the target branch firstly, and let the target brach show in the sonarqube server ui, right?

But in my case, I want to scan my target branch in a pull request when the target branch is not exists in sonarqube server, do you know how to do it?

I try to use `sonar.branch.target={my target branch}` , but it can not solve my problem..

**Comment by hoalaxanh123** [comment]
> So I have to scan the target branch firstly, and let the target brach show in the sonarqube server ui, right?

==> Yes

> But in my case, I want to scan my target branch in a pull request when the target branch is not exists in sonarqube server, do you know how to do it?

==> I don't know. But if you want to compare, you have at least 2 objects, can't compare a car with "nothing" right? Tell me what do you want to compare the new branch with, "**magic**"?
SonarQube doesn't work like that, you want to know different (coverage, smell code...) then you **have to** provide 2 branches: target branch and new branch.

**Comment by mengyan9521** [comment]
@hoalaxanh123 

Yes, you are right. I did not understand how SonarQube work. And I will scan the target branch firstly.

I am very appreciate your help, have a nice day!
