### ISSUE TITLE
Plugin does not work with Sonarqube 9.3

### ISSUE THREAD

**Issue by karnilaev** [mc1arke/sonarqube-community-branch-plugin#547]
Hello,

I have installed the plugin in the SonarQube Community EditionVersion 9.3 and now I receive a error in the end of analysis:
```
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Failed to upload report: Error 500 on http://localhost:9000/api/ce/submit?projectKey=MP_test-sonar&characteristic=branch%3Dfeature-1&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
	at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:207)
	at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:142)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: org.sonarqube.ws.client.HttpException: Error 500 on http://localhost:9000/api/ce/submit?projectKey=MP_test-sonar&characteristic=branch%3Dfeature-1&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonar.scanner.bootstrap.DefaultScannerWsClient.failIfUnauthorized(DefaultScannerWsClient.java:112)
	at org.sonar.scanner.bootstrap.DefaultScannerWsClient.call(DefaultScannerWsClient.java:75)
	at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:205)
	... 21 more
```
Without the plugin I get no errors.

**I use the following command to start analysis**
```
sonar-scanner \
  -Dsonar.projectKey=MP_test-sonar \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=SomeToken \
  -Dsonar.java.binaries=target/classes \
  -Dsonar.branch.name=feature-1
```

**Expected behavior**
Analysis goes without errors when plugin installed.

**Software Versions**
 - SonarQube Version: 9.3 (build 51899)
 - Plugin Version: 1.10.0

**Comment by beeblebrox3** [comment]
Is working fine with me. 
Did you followed all the 4 steps do install? 

```md
    1. Copy the plugin JAR file to the extensions/plugins/ directory of your SonarQube instance
    2. Add -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-${version}.jar=web to the sonar.web.javaAdditionalOpts property in your Sonarqube installation's config/sonar.properties file, e.g. sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=web
    3. Add -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-${version}.jar=ce to the sonar.ce.javaAdditionalOpts property in your Sonarqube installation's config/sonar.properties file, e.g. sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=ce
    4. Start Sonarqube, and accept the warning about using third-party plugins
```

**Comment by LocalHeroPro** [comment]
Yesterday I'm upgrading from 9.1 to 9.3, without step in 9.2.
Also changed PostgreSQL v12 to v14 on same machine using different port.
Everything working as expecting.

Keep in mind:
you HAVE TO change `${version}` to existing in your filename.

**Comment by karnilaev** [comment]
Thank you for the answers! I am going to try your advices and write here the result.

**Comment by karnilaev** [comment]
I reinstalled the application from the start and it works. Thank you again!
