### ISSUE TITLE
Plugin 1.10 does not work with SonarQube 9.3.0.51899

### ISSUE THREAD

**Issue by alfarowil** [mc1arke/sonarqube-community-branch-plugin#562]
**Describe the bug**

- I have Installed Sonarqube Community 9.3.0.51899, I have integrated in my Azure devops pipeline for Xamarin project.
- I have analized succesfully for master branch, pipeline ends with no errors, but it fails when I try to analyze another branch.
- sonar branch name property is present in project path -> sonar-project.properties, and the value is set according to branch name that is being analized:  **sonar.branch.name = develop-azure-pipelines**

- When I try to analyze another branch I'm getting the error: 

> http://XXXXXXXX.eastus.cloudapp.azure.com:9000/api/ce/submit?projectKey=XXXXXX&characteristic=branch%3Ddevelop-azure-pipelines&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

- Validating my web.log, I'm getting: 

> 2022.03.11 17:59:37 ERROR web[AX95ZvE7an1m4R3yAAE6][o.s.s.w.WebServiceEngine] Fail to process request http://XXXXXXXX.eastus.cloudapp.azure.com:9000/api/ce/submit?projectKey=XXXXXX&characteristic=branch%3Ddevelop-azure-pipelines&characteristic=branchType%3DBRANCH
> **java.lang.IllegalStateException: Current edition does not support branch feature**
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)

- Plugin was installed properly according instructions:
1. download correct jar version and paste it into extensions/plugins/
2. configure config/sonar.properties file.
3. accept warning about using third party plugin

**Expected behavior**
I Expected when I run a new analysis from another branches, ends with no errors

**Screenshots**

servers configuration:
![server_configs](https://user-images.githubusercontent.com/101355298/157926512-00bbbc4a-d293-4b9a-a95b-cdeb0757fad5.png)

failed analysis
![develop-azure-branch_failed](https://user-images.githubusercontent.com/101355298/157926515-99bfa2bb-5e01-41c1-9297-b42959837d9a.png)

success master analysis
![master_success](https://user-images.githubusercontent.com/101355298/157926516-f536fe12-0f78-4bf8-8541-f7d71012f9a6.png)

**Software Versions**
 - SonarQube Version: 9.3.0.51899
 - Plugin Version: 1.10.0

**Additional context**
I reinstalled the server, included deploying a new server and starting from zero, and same results.
I tried without sonar-project.properties file in project path and same results.
I tried setting sonar.branch.name inside of the azure task and same result.

**Comment by lastlink** [comment]
Also didn't work for me using same version. got branch not supported message

Version 9.3 (build 51899)

do we have to use an older version?

**Comment by usmonster** [comment]
It works fine for me, but instead of using the `sonar.web.javaAdditionalOpts` and `sonar.web.javaAdditionalOpts` properties I had to set the equivalent environment variables. See https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/522#issuecomment-1003333382. (Depending on some things, you may also need to specify a different path to the JAR—see also https://github.com/Oteemo/charts/issues/333#issuecomment-1032086517.)

**Comment by alfarowil** [comment]
> It works fine for me, but instead of using the `sonar.web.javaAdditionalOpts` and `sonar.web.javaAdditionalOpts` properties I had to set the equivalent environment variables. See [#522 (comment)](https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/522#issuecomment-1003333382). (Depending on some things, you may also need to specify a different path to the JAR—see also [Oteemo/charts#333 (comment)](https://github.com/Oteemo/charts/issues/333#issuecomment-1032086517).)

This is in my understanding if you are using docker, in my case I deployed Sonar over windows directly in my VM, those properties are not required in my deploy.

**Comment by zhenyu-lan** [comment]
sonarqube 9.2.4 (build 50792)也出现了同样的问题；
`
INFO: SCM Publisher is disabled
INFO: CPD Executor Calculating CPD for 0 files
INFO: CPD Executor CPD calculation finished (done) | time=1ms
INFO: Analysis report generated in 104ms, dir size=109.4 kB
INFO: Analysis report compressed in 40ms, zip size=13.1 kB
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 8.684s
INFO: Final Memory: 8M/30M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Failed to upload report: Error 500 on http://sonarqube.zhenyu.host/api/ce/submit?projectKey=vue-adminqq11q&characteristic=branch%3Dmain&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
        at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:207)
        at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:142)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: org.sonarqube.ws.client.HttpException: Error 500 on http://sonarqube.zhenyu.host/api/ce/submit?projectKey=vue-adminqq11q&characteristic=branch%3Dmain&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
        at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
        at org.sonar.scanner.bootstrap.DefaultScannerWsClient.failIfUnauthorized(DefaultScannerWsClient.java:112)
        at org.sonar.scanner.bootstrap.DefaultScannerWsClient.call(DefaultScannerWsClient.java:75)
        at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:205)
        ... 21 more
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
`

**Comment by mc1arke** [comment]
Your problem is that your configuration has `sonar.ce.javaAdditionalOpts` listed twice, the first one should be `sonar.web.javaAdditionalOpts`. Without this, the plugin will not bind to the web component of Sonarqube so the webservices will not have appropriate implementations of some endpoints in them, and the CE component will probably attempt to load classes without appropriate modification of bytecode.

**Comment by alfarowil** [comment]
Yeah!!
that was my entire fault... Now it is working so well.
thanks a lot for your time.
