### ISSUE TITLE
Sonarqube 9.4 Containerization fails due to the plugin

### ISSUE THREAD

**Issue by inugravi** [mc1arke/sonarqube-community-branch-plugin#603]
**Describe the bug**
Recently we tried to upgrade the sonarqube to 9.4 with the newly released plugin `1.11.0`. The containerization is failing with the below reason. 
```
Background initialization failed. Stopping SonarQube
java.lang.RuntimeException: Failed to load core extension Community Branch Plugin
```
I got a chance to check logs in Cloudwatch. The below are the logs.

**To Reproduce**
```
1651824123651,2022.05.06 08:02:03 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
1651824123665,2022.05.06 08:02:03 INFO  web[][o.s.s.p.DetectPluginChange] Detect plugin changes
1651824124200,2022.05.06 08:02:04 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
1651824124200,java.lang.RuntimeException: Failed to load core extension Community Branch Plugin
1651824124200,	at org.sonar.core.extension.CoreExtensionsInstaller.install(CoreExtensionsInstaller.java:78)
1651824124201,	at org.sonar.core.extension.CoreExtensionsInstaller.lambda$install$2(CoreExtensionsInstaller.java:67)
1651824124201,	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
1651824124201,	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
1651824124201,	at org.sonar.core.extension.CoreExtensionsInstaller.install(CoreExtensionsInstaller.java:67)
1651824124201,	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:643)
1651824124201,	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:196)
1651824124201,	at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:177)
1651824124201,	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:105)
1651824124201,	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:344)
1651824124201,	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:105)
1651824124202,	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:328)
1651824124202,	at java.base/java.lang.Thread.run(Thread.java:829)
1651824124202,Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: 
Invalid bean definition with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@5c8da962-org.sonar.api.config.PropertyDefinition-sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs' 
defined in null: Cannot register bean definition [Generic bean: class [org.sonar.api.config.PropertyDefinition]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null;
factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'jdk.internal.loader.ClassLoaders$AppClassLoader@5c8da962-org.sonar.api.config.PropertyDefinition-sonar.dbcleaner.daysBeforeDeletingInactiveBranchesAndPRs': 
There is already [Generic bean: class [org.sonar.api.config.PropertyDefinition]; scope=singleton; abstract=false; 
lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
1651824124202,	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:1004)
1651824124202,	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:330)
1651824124202,	at org.springframework.beans.factory.support.BeanDefinitionReaderUtils.registerBeanDefinition(BeanDefinitionReaderUtils.java:164)
1651824124202,	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:285)
1651824124202,	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:233)
1651824124202,	at org.springframework.context.annotation.AnnotationConfigApplicationContext.registerBean(AnnotationConfigApplicationContext.java:198)
1651824124202,	at org.sonar.core.platform.SpringComponentContainer.registerInstance(SpringComponentContainer.java:113)
1651824124202,	at org.sonar.core.platform.SpringComponentContainer.addExtension(SpringComponentContainer.java:129)
1651824124202,	at org.sonar.core.platform.SpringComponentContainer.addExtension(SpringComponentContainer.java:230)
1651824124202,	at org.sonar.core.platform.SpringComponentContainer.addExtension(SpringComponentContainer.java:39)
1651824124203,	at org.sonar.core.extension.CoreExtensionsInstaller$ContextImpl.addSupportedExtension(CoreExtensionsInstaller.java:141)
1651824124203,	at org.sonar.core.extension.CoreExtensionsInstaller$ContextImpl.addExtension(CoreExtensionsInstaller.java:118)
1651824124203,	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
1651824124203,	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
1651824124203,	at org.sonar.core.extension.CoreExtensionsInstaller$ContextImpl.addExtensions(CoreExtensionsInstaller.java:127)
1651824124203,	at com.github.mc1arke.sonarqube.plugin.CommunityBranchPlugin.load(CommunityBranchPlugin.java:83)
1651824124203,	at org.sonar.core.extension.CoreExtensionsInstaller.addDeclaredExtensions(CoreExtensionsInstaller.java:84)
1651824124203,	at org.sonar.core.extension.CoreExtensionsInstaller.install(CoreExtensionsInstaller.java:73)
1651824124203,	... 12 common frames omitted
1651824124287,2022.05.06 08:02:04 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
1651824124373,2022.05.06 08:02:04 INFO  app[][o.s.a.SchedulerImpl] Process[Web Server] is stopped
1651824124451,2022.05.06 08:02:04 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 143
1651824124451,2022.05.06 08:02:04 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
1651824124451,2022.05.06 08:02:04 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Expected behavior**

**Screenshots**
I have also added the ENV Variables to Docker as below.
![image](https://user-images.githubusercontent.com/81733572/167095302-cbdde3b5-d77b-499d-b1a6-ab58c02c5131.png)

**Software Versions**
 - SonarQube Version: 9.4
 - Plugin Version: 1.11.0

**Additional context**

**Comment by danilooliveira88** [comment]
I am with equals problema here

**Comment by mc1arke** [comment]
I'd need to see a copy of your container definition (Dockerfile?) to diagnose this.
