### ISSUE TITLE
Caused by: com.google.gson.JsonIOException: java.io.IOException: CRC: actual 0x8cad70b4 != expected 0x328b9db4

### ISSUE THREAD

**Issue by racodond** [mc1arke/sonarqube-community-branch-plugin#621]
**Describe the bug**
We face the following issue while running SonarQube analysis:
Caused by: com.google.gson.JsonIOException: java.io.IOException: CRC: actual 0x8cad70b4 != expected 0x328b9db4

 It is on a specific project.
It was working before on this project.

**Software Versions**
 - SonarQube Version: 8.9.5
 - Plugin Version: 1.8.1

Here's the full stack trace:
[13:12:42.203+02:00] - INFO: Load project branches
[13:12:42.203+02:00] - INFO: Load project branches (done) | time=44ms
[13:12:42.203+02:00] - INFO: Load project pull requests
[13:12:42.568+02:00] - INFO: EXECUTION FAILURE
[13:12:42.568+02:00] - INFO: ------------------------------------------------------------------------
[13:12:42.568+02:00] - INFO: Total time: 5.412s
[13:12:42.568+02:00] - INFO: Final Memory: 10M/61M
[13:12:42.568+02:00] - INFO: ------------------------------------------------------------------------
[13:12:42.568+02:00] - ERROR: Error during SonarScanner execution
[13:12:42.568+02:00] - java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.scan.filesystem.InputComponentStore
[13:12:42.568+02:00] - 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:66)
[13:12:42.568+02:00] - 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
[13:12:42.568+02:00] - 	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
[13:12:42.568+02:00] - 	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
[13:12:42.569+02:00] - 	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
[13:12:42.569+02:00] - 	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
[13:12:42.569+02:00] - 	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
[13:12:42.569+02:00] - 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[13:12:42.569+02:00] - 	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
[13:12:42.569+02:00] - 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
[13:12:42.569+02:00] - 	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
[13:12:42.569+02:00] - 	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
[13:12:42.569+02:00] - 	at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
[13:12:42.569+02:00] - 	at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
[13:12:42.569+02:00] - 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
[13:12:42.569+02:00] - 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
[13:12:42.569+02:00] - 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[13:12:42.569+02:00] - 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[13:12:42.569+02:00] - 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:150)
[13:12:42.569+02:00] - 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[13:12:42.569+02:00] - 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[13:12:42.569+02:00] - 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
[13:12:42.569+02:00] - 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
[13:12:42.569+02:00] - 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[13:12:42.569+02:00] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:12:42.569+02:00] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:12:42.569+02:00] - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:12:42.570+02:00] - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:12:42.570+02:00] - 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[13:12:42.570+02:00] - 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[13:12:42.570+02:00] - 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
[13:12:42.570+02:00] - 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
[13:12:42.570+02:00] - 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
[13:12:42.570+02:00] - 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
[13:12:42.570+02:00] - 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[13:12:42.570+02:00] - Caused by: java.lang.IllegalStateException: Unable to load component interface org.sonar.scanner.scan.branch.BranchConfiguration
[13:12:42.570+02:00] - 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:66)
[13:12:42.570+02:00] - 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
[13:12:42.570+02:00] - 	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
[13:12:42.570+02:00] - 	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
[13:12:42.570+02:00] - 	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
[13:12:42.570+02:00] - 	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
[13:12:42.570+02:00] - 	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
[13:12:42.570+02:00] - 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[13:12:42.570+02:00] - 	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
[13:12:42.570+02:00] - 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
[13:12:42.570+02:00] - 	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
[13:12:42.570+02:00] - 	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
[13:12:42.570+02:00] - 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
[13:12:42.570+02:00] - 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
[13:12:42.570+02:00] - 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:64)
[13:12:42.570+02:00] - 	... 34 more
[13:12:42.570+02:00] - Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.scan.branch.ProjectPullRequests
[13:12:42.571+02:00] - 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:66)
[13:12:42.571+02:00] - 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
[13:12:42.571+02:00] - 	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
[13:12:42.571+02:00] - 	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.SingleMemberInjector.getMemberArguments(SingleMemberInjector.java:61)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.MethodInjector.getMemberArguments(MethodInjector.java:100)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:112)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
[13:12:42.571+02:00] - 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
[13:12:42.571+02:00] - 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
[13:12:42.571+02:00] - 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:64)
[13:12:42.571+02:00] - 	... 48 more
[13:12:42.571+02:00] - Caused by: com.google.gson.JsonIOException: java.io.IOException: CRC: actual 0x8cad70b4 != expected 0x328b9db4
[13:12:42.571+02:00] - 	at com.google.gson.Gson.assertFullConsumption(Gson.java:910)
[13:12:42.571+02:00] - 	at com.google.gson.Gson.fromJson(Gson.java:871)
[13:12:42.571+02:00] - 	at com.github.mc1arke.sonarqube.plugin.scanner.CommunityProjectPullRequestsLoader.load(CommunityProjectPullRequestsLoader.java:98)
[13:12:42.571+02:00] - 	at org.sonar.scanner.scan.branch.ProjectPullRequestsProvider.provide(ProjectPullRequestsProvider.java:47)
[13:12:42.571+02:00] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:12:42.571+02:00] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:12:42.571+02:00] - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:12:42.571+02:00] - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:12:42.571+02:00] - 	at org.picocontainer.injectors.MethodInjector.invokeMethod(MethodInjector.java:129)
[13:12:42.572+02:00] - 	at org.picocontainer.injectors.MethodInjector.access$000(MethodInjector.java:39)
[13:12:42.572+02:00] - 	at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:113)
[13:12:42.572+02:00] - 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
[13:12:42.572+02:00] - 	at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
[13:12:42.572+02:00] - 	at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
[13:12:42.572+02:00] - 	at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
[13:12:42.572+02:00] - 	at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
[13:12:42.572+02:00] - 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
[13:12:42.572+02:00] - 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
[13:12:42.572+02:00] - 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:64)
[13:12:42.572+02:00] - 	... 63 more
[13:12:42.572+02:00] - Caused by: java.io.IOException: CRC: actual 0x8cad70b4 != expected 0x328b9db4
[13:12:42.572+02:00] - 	at okio.GzipSource.checkEqual(GzipSource.kt:197)
[13:12:42.572+02:00] - 	at okio.GzipSource.consumeTrailer(GzipSource.kt:164)
[13:12:42.572+02:00] - 	at okio.GzipSource.read(GzipSource.kt:81)
[13:12:42.572+02:00] - 	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
[13:12:42.572+02:00] - 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
[13:12:42.572+02:00] - 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
[13:12:42.572+02:00] - 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[13:12:42.572+02:00] - 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
[13:12:42.572+02:00] - 	at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211)
[13:12:42.572+02:00] - 	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1291)
[13:12:42.572+02:00] - 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1329)
[13:12:42.572+02:00] - 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:539)
[13:12:42.572+02:00] - 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
[13:12:42.572+02:00] - 	at com.google.gson.Gson.assertFullConsumption(Gson.java:904)
[13:12:42.572+02:00] - 	... 81 more
[13:12:42.572+02:00] - ERROR:

**Comment by racodond** [comment]
It seems that it is not directly linked to your plugin.
Downgrading the sonar-scanner to 4.6 made the analysis work again.
