### ISSUE TITLE
Dockerized SonarQube fails to start with plugin 1.12

### ISSUE THREAD

**Issue by mysiar** [mc1arke/sonarqube-community-branch-plugin#655]
**Describe the bug**
SonarQube doesn't start with plugin

**To Reproduce**
Tried to used it in config sonar.properties or in ENV for container the same error
```
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar
```
**Error message**
```
sonarqube    | 18:16:05.389 [main] INFO com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Loading agent
sonarqube    | Exception in thread "main" java.lang.reflect.InvocationTargetException
sonarqube    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sonarqube    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sonarqube    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sonarqube    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sonarqube    | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
sonarqube    | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
sonarqube    | Caused by: java.lang.IllegalArgumentException: Invalid/missing agent argument
sonarqube    | 	at com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent.lambda$premain$0(CommunityBranchAgent.java:51)
sonarqube    | 	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
sonarqube    | 	at com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent.premain(CommunityBranchAgent.java:51)
sonarqube    | 	... 6 more
sonarqube    | *** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
sonarqube    | FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
sonarqube    | 2022.08.14 18:16:05 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [Web Server]: 134
sonarqube    | 2022.08.14 18:16:05 INFO  app[][o.s.a.SchedulerImpl] Process[Web Server] is stopped
sonarqube    | 2022.08.14 18:16:05 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 143
sonarqube    | 2022.08.14 18:16:05 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
sonarqube    | 2022.08.14 18:16:05 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Software Versions**
 - SonarQube Version: 9.6.0.59041
 - Plugin Version: 1.12.0
- Used SonarQube Docker: https://github.com/mysiar/sonarqube-dockerized

**Comment by brother** [comment]
Try using 9.5 until a fix is available.

**Comment by mysiar** [comment]
@brother seems to be problem as well with

```

**Comment by brother** [comment]
That's interesting. I use 9.5 in docker and the 1.12 plugin seems to work fine.

**Comment by mc1arke** [comment]
@mysiar  You're missing the `=web` and `=ce` arguments on the end of the agent entries for each of your `additionalProperties` lines
