### ISSUE TITLE
java.lang.IllegalStateException: Current edition does not support branch feature with SonarQube 8.9.9lts and Community Branch plugin 1.8.2

### ISSUE THREAD

**Issue by praharshr92** [mc1arke/sonarqube-community-branch-plugin#671]
**Describe the bug**
Getting a Fail to process request http://dev-inspect.dev.xxxx.io/api/ce/submit?projectKey=1p%3Aspringboot-example-spacev2&projectName=springboot-example-spacev2&characteristic=branch%3Dmaster&characteristic=branchType%3DBRANCH
 java.lang.IllegalStateException: Current edition does not support branch feature

Context
After installing the plugin following these directions I am still facing the issue
https://github.com/mc1arke/sonarqube-community-branch-plugin#installation

```
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 2022.10.07 20:19:54 ERROR web[AYO0BxUROdCmBZcvAANW][o.s.s.w.WebServiceEngine] Fail to process request http://dev-inspect.dev.xxxx.io/api/ce/submit?projectKey=1p%3Aspringboot-example-spacev2&projectName=springboot-example-spacev2&characteristic=branch%3Dmaster&characteristic=branchType%3DBRANCH
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube java.lang.IllegalStateException: Current edition does not support branch feature
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.ce.queue.BranchSupport.createComponentKey(BranchSupport.java:59)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.ce.queue.ReportSubmitter.submit(ReportSubmitter.java:82)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.ce.ws.SubmitAction.handle(SubmitAction.java:100)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1651)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
dev-inspect-sonarqube-ff866f77d-9pt9f sonarqube 	at java.base/java.lang.Thread.run(Unknown Source)

```

**Software Versions**
 - SonarQube Version: 8.9.9lts
 - Plugin Version: 1.8.2

**Comment by praharshr92** [comment]
looks like sonar.web.javaAdditionalOpts is ignored by web starter

I solved this!
