### ISSUE TITLE
java.lang.ClassNotFoundException: org.sonar.server.almsettings.MultipleAlmFeatureProvider

### ISSUE THREAD

**Issue by mgexm** [mc1arke/sonarqube-community-branch-plugin#682]
**Describe the bug**
When using the plugin 1.13.0 and Sonarqube Community 9.7 I see the following exception

15:30:42.365 [main] INFO com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent - Loading agent
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.ClassNotFoundException: org.sonar.server.almsettings.MultipleAlmFeatureProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent.redefineEdition(CommunityBranchAgent.java:93)
	at com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent.premain(CommunityBranchAgent.java:56)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

**To Reproduce**
docker build --build-arg SONARQUBE_VERSION=9.7.0-community --build-arg PLUGIN_VERSION=1.13.0-SNAPSHOT -t sonarqube:9.7 .

**Expected behavior**

**Screenshots**

**Software Versions**
 - SonarQube Version: 9.7
 - Plugin Version: 1.13.0

**Additional context**

**Comment by mgexm** [comment]
this is a duplicate of https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/674 ... my apologies !
