### ISSUE TITLE
Sonarqube-9.x logging Current edition does not support branch feature

### ISSUE THREAD

**Issue by adrianovieira** [mc1arke/sonarqube-community-branch-plugin#687]
**Describe the bug**
Trying to  have branch analised even using SonarQube-9.x Community edition we got the logging message:

.sonar-scanner
```shell
$ sonar-scanner -D sonar.branch.name=$(git branch --show-current) ...
```

.error
```
java.lang.IllegalStateException: Current edition does not support branch feature
```

**To Reproduce**
1. setup sonar-9.5+ server
2. create a project token
3. execute sonar-scanner

 ```
 sonar-scanner -D sonar.projectVersion=$(git branch --show-current)-$(git rev-parse --short HEAD) \
               -D sonar.branch.name=$(git branch --show-current) \
               -D sonar.host.url=http://sonar:9000 \
               -D sonar.projectKey=my-project \
               -D sonar.login=sqp_a9679040cde0ea13871de2dfa313c60cb4168fec
 ```

4. See error on sonar server logging

**Expected behavior**
Sonar create analisys of the branch

**Screenshots**
NA

**Software Versions**
 - SonarQube Version: (sonarqube docker images)
   - `sonarqube:9.5-community` 
   - `sonarqube:9.6-community`
   - `sonarqube:9.7-community`
 - Plugin Version: `1.12.0`
 - Sonar-scanner version: `4.7.0.2747`

**Additional context**

Tested conf/sonar.properties setup:

1. as mentioned on README

 ```properties
 sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=web
 sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=ce
 ```

other settings attempts:

<Details>

2. conf/sonar.properties
 ```
 sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
 ```

3. conf/sonar.properties
 ```
 sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
 ```

4. conf/sonar.properties
 ```
 sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0
 ```

5. conf/sonar.properties
 ```
 sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0
 ```

6. conf/sonar.properties
 ```
 sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
 sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
 ```

7. conf/sonar.properties
 ```
 sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0
 sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0
 ```
</Details>

### Docker env test

Download the plugin to `./sonar-plugins/sonarqube-community-branch-plugin-1.12.0.jar` before.

`docker compose up -d`

- `docker-compose.yml`:

<Details>

```yaml
---
version: "3"
services:
  sonar:
    # image: sonarqube:9.5-community
    # image: sonarqube:9.6-community
    image: sonarqube:9.7-community
    depends_on:
      - sonar-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: notsecure
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - ./conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./sonar-plugins/:/opt/sonarqube/extensions/plugins/
    ports:
      - "9000:9000"
  sonar-db:
    image: postgres:12
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: notsecure
```

</Details>

- `./conf/sonar.properties`:

<Details>

```properties
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=ce
# sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=web
# sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
```
</Details>

#### sonar-scanner 

- logging-errors:
 
<Details>

  ```
12:14:48.541 ERROR: Error during SonarScanner execution
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ClassRealm{javascript}-org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl': Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AnalysisTempFolder' defined in org.sonar.scanner.analysis.AnalysisTempFolderProvider: Unsatisfied dependency expressed through method 'provide' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DefaultInputProject' defined in org.sonar.scanner.scan.InputProjectProvider: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.sonar.api.batch.fs.internal.DefaultInputProject]: Factory method 'provide' threw exception; nested exception is Validation of project failed:
  o To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:187)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AnalysisTempFolder' defined in org.sonar.scanner.analysis.AnalysisTempFolderProvider: Unsatisfied dependency expressed through method 'provide' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DefaultInputProject' defined in org.sonar.scanner.scan.InputProjectProvider: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.sonar.api.batch.fs.internal.DefaultInputProject]: Factory method 'provide' threw exception; nested exception is Validation of project failed:
  o To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 31 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DefaultInputProject' defined in org.sonar.scanner.scan.InputProjectProvider: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.sonar.api.batch.fs.internal.DefaultInputProject]: Factory method 'provide' threw exception; nested exception is Validation of project failed:
  o To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 45 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.sonar.api.batch.fs.internal.DefaultInputProject]: Factory method 'provide' threw exception; nested exception is Validation of project failed:
  o To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 59 more
Caused by: Validation of project failed:
  o To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required. See https://redirect.sonarsource.com/doc/branches.html for more information.

  ```

 </Details>
 
  - logging:

 <Details>

  ```
    12:14:47.029 INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
    12:14:47.032 INFO: Project root configuration file: /usr/src/voucher-landing-page-api/sonar-project.properties
    12:14:47.061 INFO: SonarScanner 4.7.0.2747
    12:14:47.062 INFO: Java 11.0.17 Alpine (64-bit)
    12:14:47.063 INFO: Linux 5.10.102.1-microsoft-standard-WSL2 amd64
    12:14:47.159 DEBUG: keyStore is : 
    12:14:47.160 DEBUG: keyStore type is : pkcs12
    12:14:47.161 DEBUG: keyStore provider is : 
    12:14:47.162 DEBUG: init keystore
    12:14:47.164 DEBUG: init keymanager of type SunX509
    12:14:47.268 DEBUG: Create: /code/.sonar/cache
    12:14:47.269 INFO: User cache: /code/.sonar/cache
    12:14:47.269 DEBUG: Create: /code/.sonar/cache/_tmp
    12:14:47.272 DEBUG: Extract sonar-scanner-api-batch in temp...
    12:14:47.275 DEBUG: Get bootstrap index...
    12:14:47.276 DEBUG: Download: http://sonar:9000/batch/index
    12:14:47.310 DEBUG: Get bootstrap completed
    12:14:47.314 DEBUG: Create isolated classloader...
    12:14:47.322 DEBUG: Start temp cleaning...
    12:14:47.325 DEBUG: Temp cleaning done
    12:14:47.326 INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
    12:14:47.329 INFO: Project root configuration file: /usr/src/voucher-landing-page-api/sonar-project.properties
    12:14:47.333 DEBUG: Execution getVersion
    12:14:47.350 INFO: Analyzing on SonarQube server 9.5.0.56709
    12:14:47.352 INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
    12:14:47.353 DEBUG: Work directory: /usr/src/voucher-landing-page-api/.scannerwork
    12:14:47.355 DEBUG: Execution execute
    12:14:47.608 DEBUG: Community 9.5.0.56709
    12:14:47.830 INFO: Load global settings
    12:14:47.878 DEBUG: GET 200 http://sonar:9000/api/settings/values.protobuf | time=46ms
    12:14:47.906 INFO: Load global settings (done) | time=76ms
    12:14:47.908 INFO: Server id: 303924D4-AYRhb1glJWNLZlRrW27N
    12:14:47.916 INFO: User cache: /code/.sonar/cache
    12:14:47.919 INFO: Load/download plugins
    12:14:47.920 INFO: Load plugins index
    12:14:47.927 DEBUG: GET 200 http://sonar:9000/api/plugins/installed | time=7ms
    12:14:47.960 INFO: Load plugins index (done) | time=40ms
    12:14:48.027 INFO: Load/download plugins (done) | time=108ms
    12:14:48.070 DEBUG: Plugins:
    12:14:48.070 DEBUG:   * Python Code Quality and Security 3.13.0.9611 (python)
    12:14:48.071 DEBUG:   * Go Code Quality and Security 1.9.0.3429 (go)
    12:14:48.071 DEBUG:   * JaCoCo 1.1.1.1157 (jacoco)
    12:14:48.072 DEBUG:   * Kotlin Code Quality and Security 2.9.0.1147 (kotlin)
    12:14:48.072 DEBUG:   * IaC Code Quality and Security 1.7.0.2012 (iac)
    12:14:48.072 DEBUG:   * JavaScript/TypeScript/CSS Code Quality and Security 9.3.0.18033 (javascript)
    12:14:48.073 DEBUG:   * Ruby Code Quality and Security 1.9.0.3429 (ruby)
    12:14:48.073 DEBUG:   * Scala Code Quality and Security 1.9.0.3429 (sonarscala)
    12:14:48.074 DEBUG:   * C# Code Quality and Security 8.40.0.48530 (csharp)
    12:14:48.074 DEBUG:   * Java Code Quality and Security 7.12.0.29739 (java)
    12:14:48.074 DEBUG:   * HTML Code Quality and Security 3.6.0.3106 (web)
    12:14:48.075 DEBUG:   * Flex Code Quality and Security 2.7.0.2865 (flex)
    12:14:48.075 DEBUG:   * XML Code Quality and Security 2.5.0.3376 (xml)
    12:14:48.075 DEBUG:   * PHP Code Quality and Security 3.23.1.8766 (php)
    12:14:48.076 DEBUG:   * Text file Code Quality and Security 1.1.0.282 (text)
    12:14:48.076 DEBUG:   * VB.NET Code Quality and Security 8.40.0.48530 (vbnet)
    12:14:48.076 DEBUG:   * Configuration detection fot Code Quality and Security 1.2.0.267 (config)
    12:14:48.490 INFO: Process project properties
    12:14:48.505 INFO: Process project properties (done) | time=15ms
    12:14:48.508 INFO: Execute project builders
    12:14:48.509 DEBUG: Execute project builder: org.sonar.plugins.csharp.CSharpGlobalProtobufFileProcessor
    12:14:48.510 DEBUG: Execute project builder: org.sonar.plugins.vbnet.VbNetGlobalProtobufFileProcessor
    12:14:48.511 INFO: Execute project builders (done) | time=3ms
    12:14:48.519 INFO: ------------------------------------------------------------------------
    12:14:48.520 INFO: EXECUTION FAILURE
    12:14:48.520 INFO: ------------------------------------------------------------------------
    12:14:48.521 INFO: Total time: 1.497s
    12:14:48.540 INFO: Final Memory: 7M/27M
    12:14:48.541 INFO: ------------------------------------------------------------------------
  ```
  </Details>

**Comment by nixel2007** [comment]
as it mentioned in README, it should be:
```
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=web
```

**Comment by adrianovieira** [comment]
> as it mentioned in README, it should be:
> 
> ```
> sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
> sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=web
> ```

No! There is:

.Readme
```
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=ce
```

.as you mentioned
```
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0=ce
```

But neither way works.

**Comment by brother** [comment]
> image: sonarqube:9.7-community

Sonarqube 9.7.x and plugin 1.12.0 is not compatible. Use 9.6.1 or earlier.

see also #674 and #679.

**Comment by hawk911** [comment]
I have the same problem but I don't use docker.

**Comment by brother** [comment]
@hawk911 use a lower sonarqube version. see my previous reply and find the links.

**Comment by hawk911** [comment]
> @hawk911 use a lower sonarqube version. see my previous reply and find the links.

Thank you. I will!

**Comment by adrianovieira** [comment]
> > image: sonarqube:9.7-community
> 
> Sonarqube 9.7.x and plugin 1.12.0 is not compatible. Use 9.6.1 or earlier.
> 
> see also #674 and #679.

Hi. thx for your reply.

Yes! I've done it already. As you maybe can notice in the issue description I wrote.

I tested with `sonarqube:9.5-community`, `sonarqube:9.6-community`, and `sonarqube:9.7-community`, but neither works.
And the environment setup and files content, I also shared in the issue description:
- `docker-compose.yml`
- `conf/sonar.properties`

**Comment by brother** [comment]
You say you tested indeed but the file shared is for 9.7. 

I am myself using the plugin with 9.6.1 and it works perfectly when following the readme. No doubt at all.

**Comment by brother** [comment]
```
$ grep javaAdd /var/lib/docker/volumes/sonarqube_sonarqube_conf/_data/sonar.properties
sonar.web.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=web
sonar.ce.javaAdditionalOpts=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.12.0.jar=ce
```

with docker-compose.yml, 

```
version: "3"

services:
  sonarqube:
    image: sonarqube:9.6.1-community
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://host.docker.internal:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
```

**Comment by adrianovieira** [comment]
> You say you tested indeed but the file shared is for 9.7.
> 
> I am myself using the plugin with 9.6.1 and it works perfectly when following the readme. No doubt at all.

No! As you can notice on that file there are three images you can switch and test:

``` yaml
...
    # image: sonarqube:9.5-community
    # image: sonarqube:9.6-community
    image: sonarqube:9.7-community
...
```

**Comment by brother** [comment]
Ok fine. Your instance is not working. Mine is. Any day now you will find a way I am sure.

**Comment by naviat** [comment]
From my side, It's not working with version 9.6.1-community too
