### ISSUE TITLE
Problem with hasProjectPermission

### ISSUE THREAD

**Issue by FelixBrunet** [mc1arke/sonarqube-community-branch-plugin#801]
Someone has provide a fix here for new version of sonar version, im using 10.2.0.77647

https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/782

But using this version : 1.15.0-SNAPSHOT

I got this error now:

Caused by: java.lang.NoSuchMethodError: 'boolean org.sonar.server.user.UserSession.hasProjectPermission(java.lang.String, org.sonar.db.project.ProjectDto)'
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction.checkPermission(ListAction.java:108)
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction.handleProjectRequest(ListAction.java:79)
	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ProjectWsAction.handle(ProjectWsAction.java:61)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:111)
	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
	at org.sonar.server.platform.web.MasterServletFilter$JavaxFilterAdapter.doFilter(MasterServletFilter.java:227)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:198)
	at org.sonar.server.platform.web.MasterServletFilter$HttpFilterChainAdapter.doFilter(MasterServletFilter.java:241)
	at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
	at org.sonar.server.platform.web.MasterServletFilter$JavaxFilterAdapter.doFilter(MasterServletFilter.java:227)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:198)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:146)
	at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
	... 128 common frames omitted

**Comment by DiegoGi** [comment]
I have the same problem in version 10.2 of SonarQube running on Windows

**Comment by DiegoGi** [comment]
> Someone has provide a fix here for new version of sonar version, im using 10.2.0.77647
> 
> #782
> 
> But using this version : 1.15.0-SNAPSHOT
> 
> I got this error now:
> 
> Caused by: java.lang.NoSuchMethodError: 'boolean org.sonar.server.user.UserSession.hasProjectPermission(java.lang.String, org.sonar.db.project.ProjectDto)' at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction.checkPermission(ListAction.java:108) at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction.handleProjectRequest(ListAction.java:79) at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ProjectWsAction.handle(ProjectWsAction.java:61) at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:111) at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84) at org.sonar.server.platform.web.MasterServletFilter$JavaxFilterAdapter.doFilter(MasterServletFilter.java:227) at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:198) at org.sonar.server.platform.web.MasterServletFilter$HttpFilterChainAdapter.doFilter(MasterServletFilter.java:241) at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66) at org.sonar.server.platform.web.MasterServletFilter$JavaxFilterAdapter.doFilter(MasterServletFilter.java:227) at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:198) at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:146) at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584) at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ... 128 common frames omitted

This PR fix the problem
https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/797

**Comment by mc1arke** [comment]
Support for Sonarqube 10.2 was released in v1.17.1 of the plugin
