### ISSUE TITLE
An error has occurred. Please contact your administrator - Access the project from the UI

### ISSUE THREAD

**Issue by tejas-dhamdhere** [mc1arke/sonarqube-community-branch-plugin#803]
Sonarqube version - 9.9.1
communityBranchPlugin' version : 1.14.0 
Web logs... 

```
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'communityBranchPlugin' version : 1.14.0 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'config' version : 1.2.0.267 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'csharp' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'flex' version : 2.8.0.3166 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'go' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'iac' version : 1.11.0.2847 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'jacoco' version : 1.3.0.1538 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'java' version : 7.16.0.30901 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'javascript' version : 9.13.0.20537 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'kotlin' version : 2.12.0.1956 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'perl' version : 0.5.6 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'php' version : 3.27.1.9352 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'python' version : 3.24.0.10784 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'ruby' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'sonarscala' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'text' version : 2.0.2.1090 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'vbnet' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'web' version : 3.7.1.3306 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xml' version : 2.7.0.3820 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xquery' version : 1.0-SNAPSHOT has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'communityBranchPlugin' version : 1.14.0 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'config' version : 1.2.0.267 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'csharp' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'flex' version : 2.8.0.3166 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'go' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'iac' version : 1.11.0.2847 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'jacoco' version : 1.3.0.1538 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'java' version : 7.16.0.30901 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'javascript' version : 9.13.0.20537 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'kotlin' version : 2.12.0.1956 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'perl' version : 0.5.6 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'php' version : 3.27.1.9352 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'python' version : 3.24.0.10784 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'ruby' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'sonarscala' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'text' version : 2.0.2.1090 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'vbnet' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'web' version : 3.7.1.3306 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xml' version : 2.7.0.3820 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xquery' version : 1.0-SNAPSHOT has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'communityBranchPlugin' version : 1.14.0 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'config' version : 1.2.0.267 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'csharp' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'flex' version : 2.8.0.3166 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'go' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'iac' version : 1.11.0.2847 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'jacoco' version : 1.3.0.1538 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'java' version : 7.16.0.30901 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'javascript' version : 9.13.0.20537 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'kotlin' version : 2.12.0.1956 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'perl' version : 0.5.6 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'php' version : 3.27.1.9352 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'python' version : 3.24.0.10784 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'ruby' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'sonarscala' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'text' version : 2.0.2.1090 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'vbnet' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'web' version : 3.7.1.3306 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xml' version : 2.7.0.3820 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xquery' version : 1.0-SNAPSHOT has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'communityBranchPlugin' version : 1.14.0 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'config' version : 1.2.0.267 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'csharp' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'flex' version : 2.8.0.3166 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'go' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'iac' version : 1.11.0.2847 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'jacoco' version : 1.3.0.1538 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'java' version : 7.16.0.30901 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'javascript' version : 9.13.0.20537 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'kotlin' version : 2.12.0.1956 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'perl' version : 0.5.6 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'php' version : 3.27.1.9352 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'python' version : 3.24.0.10784 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'ruby' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'sonarscala' version : 1.11.0.3905 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'text' version : 2.0.2.1090 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'vbnet' version : 8.51.0.59060 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'web' version : 3.7.1.3306 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xml' version : 2.7.0.3820 has not been found on the update center.
2023.09.14 09:54:27 INFO  web[AYp43/oNBpKO81N/G0KR][o.s.u.c.UpdateCenter] The plugin 'xquery' version : 1.0-SNAPSHOT has not been found on the update center.
2023.09.14 09:49:40 ERROR web[AYp43/oNBpKO81N/Gzpf][o.s.s.w.WebServiceEngine] Fail to process request http://xyz.sonar.com/api/project_pull_requests/list?project=XYZ_V1
java.lang.NullPointerException: Pull request data should be available for branch type PULL_REQUEST
        at java.base/java.util.Objects.requireNonNull(Objects.java:235)
        at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction.addPullRequest(ListAction.java:123)
        at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction.lambda$handleProjectRequest$2(ListAction.java:102)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction.handleProjectRequest(ListAction.java:102)
        at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ProjectWsAction.handle(ProjectWsAction.java:61)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:111)
        at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:153)
        at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:153)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:116)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.sonar.server.platform.web.CspFilter.doFilter(CspFilter.java:63)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:60)
        at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:47)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:57)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:64)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:115)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.sonar.server.app.SecureErrorReportValve.invoke(SecureErrorReportValve.java:37)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

As per the Sonar support issue is with - communityBranchPlugin'
https://community.sonarsource.com/t/an-error-has-occurred-please-contact-your-administrator-access-the-project-from-the-ui/99174

Please check

**Comment by Rolika4** [comment]
The same error in UI
Sonarqube version - 9.9.2
communityBranchPlugin' version : 1.14.0

**Comment by Rolika4** [comment]
Any updates here?

**Comment by mc1arke** [comment]
No updates as you've not given enough detail to allow us to replicate this: the error message indicates the project is in an invalid state, but gives no indication as to the steps you'd taken previously to cause that to happem

**Comment by mc1arke** [comment]
Closing as 'Not planned' due to lack of replication steps

**Comment by wllianwd** [comment]
@mc1arke happen 3 times for us, the problem was that we had entries in the table `project_branches` with type `PULL_REQUEST` and NULL values for columns `merge_branch_uuid` and `pull_request_binary`. I'm not sure how those entries were created as null. Manually removing those entries fixed the issue.

```
SONAR_VERSION=9.9.4.87374
COMMUNITY_BRANCH_PLUGIN_VERSION=1.14.0
```

**Comment by dhutchison** [comment]
I don't think this happens every time, but the pattern I've spotted is this can occur if a PR is scanned before the main branch has been scanned (this scan rightly fails as the main branch hasn't been scanned). 

Subsequently scanning the main branch seems to leave it in this broken state. The API reports the main branch scan as being a success, but the web dashboard is unable to load the project.

**Comment by itineric** [comment]
This error happens when renaming a project in gitlab. I used @wllianwd hack and removed dirty data from the database (project_branches table), now its working again.
