### ISSUE TITLE
 Error during SonarScanner execution java.lang.IllegalStateException: Failed to upload report

### ISSUE THREAD

**Issue by sairamab** [mc1arke/sonarqube-community-branch-plugin#895]
**Describe the bug**
We are using plugin version 1.16.0 for sonarqube version 10.1.0. After analysing a project with sonarscanner we see the error as 
```
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Failed to upload report: Error 500 on https://www.xyz.com/api/ce/submit?projectKey=org.sonarqube%3Ascmgalaxy1&projectName=NokiaX&characteristic=branch%3Dmain&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
        at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:227)
        at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:155)
        at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:376)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:71)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:65)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
        at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: org.sonarqube.ws.client.HttpException: Error 500 on https://www.xyz.com/api/ce/submit?projectKey=org.sonarqube%3Ascmgalaxy1&projectName=NokiaX&characteristic=branch%3Dmain&characteristic=branchType%3DBRANCH : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
        at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
        at org.sonar.scanner.bootstrap.DefaultScannerWsClient.failIfUnauthorized(DefaultScannerWsClient.java:128)
        at org.sonar.scanner.bootstrap.DefaultScannerWsClient.call(DefaultScannerWsClient.java:89)
        at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:225)
        ... 21 more
ERROR:
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

**Expected behavior**
execution success

**Software Versions**
 - SonarQube Version:10.1.0
 - Plugin Version: 1.16.0

**Comment by mc1arke** [comment]
I suspect your Sonarqube instance doesn't have the plugin installed properly. Please provide a copy of your CE and Web logs, ideally showing the startup of your server, and submission of an attempted analysis.

**Comment by sairamab** [comment]
Hi Sorry for the late reply.
I don't have that instance to fetch logs.
But below is the way I used in values.yaml file for installing plugin


plugins:
  install: 
    - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.17.1/sonarqube-community-branch-plugin-1.17.1.jar"
   
  lib:
    - sonarqube-community-branch-plugin-1.17.1.jar
    
    
#jvmOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar=web"
#jvmOpts: ""
sonar.web.javaOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.16.0.jar=web"
#sonar.web.javaOpts: ""

#jvmCeOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar=ce"
#jvmCeOpts: ""
sonar.ce.javaOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.16.0.jar=ce"
#sonar.ce.javaOpts: ""


Could you please help if this is the correct way

**Comment by mc1arke** [comment]
Your values don't seem to align - 1.17.1 in the install/download list but 1.16.0 in the javaOpts configuration.

**Comment by sairamab** [comment]
yes, sorry for wrong info I have used as below (sonarqube version-10.2.1, plugin version- 1.17.1) 
sonar.web.javaOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.17.1.jar=web"
sonar.ce.javaOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.17.1.jar=ce"

Majorly I want to know is the above correct way to proceed plugin configuration for later versions of sonarqube, 
because earlier I was using as below for older versions.
jvmOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar=web
jvmCeOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar=ce"

but later chart of sonarqube has
(DEPRECATED) Please use SONAR_WEB_JAVAOPTS or sonar.web.javaOpts

**Comment by mc1arke** [comment]
Sorry, I can't particularly comment on configuring managing helm as I don't test with the Sonarqube chart. Other community members might be able to support you, but I'm closing this as there's no clear bug here.
