### ISSUE TITLE
Github API is returning 'Expected string or block string, but it was malformed' 

### ISSUE THREAD

**Issue by Tsuesun** [mc1arke/sonarqube-community-branch-plugin#959]
**Describe the bug**
Github API is returning 'Expected string or block string, but it was malformed' when trying to decorate the PR. This occurred suddenly today.

**To Reproduce**
Unknown

**Expected behavior**
Github API returns a 200 and pull request decoration completes

**Software Versions**
 - SonarQube Version: [Community EditionVersion 10.0 (build 68432)]
 - Plugin Version: [1.16.0]

**Additional context**
```
2024.09.03 00:57:04 ERROR ce[AZG1YpEQP4vylyjzcyxf][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalStateException: Could not decorate Pull Request on Github
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:95)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:146)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:102)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:93)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:89)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:61)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: An error was returned in the response from the Github API:
- Error{message='Expected string or block string, but it was malformed', locations=[Location{line='1', column='70'}]}
	at com.github.mc1arke.sonarqube.plugin.almclient.github.v4.GraphqlGithubClient.executeRequest(GraphqlGithubClient.java:246)
	at com.github.mc1arke.sonarqube.plugin.almclient.github.v4.GraphqlGithubClient.createCheckRun(GraphqlGithubClient.java:111)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:87)
	... 21 common frames omitted
```

**Comment by fegbers** [comment]
We have had the same problem since yesterday.

**Comment by mc1arke** [comment]
Is this Github cloud or Github enterprise (self hosted)?

**Comment by Tsuesun** [comment]
Github cloud in my case

**Comment by fegbers** [comment]
GitHub cloud as well

**Comment by pedrocarrico** [comment]
I'm also having this exact same issue since yesterday and same message on the logs as @Tsuesun 

- SonarQube Version: [Community Edition v10.6 (92116)]
- Plugin Version: [1.19.1]
-  Github cloud

**Comment by kienw** [comment]
Same issue here.

* SonarQube Version: [Community Edition v10.5.1 (90531)]
* Plugin Version: [1.19.0]
* Github cloud

**Comment by anaszakarneh1** [comment]
We've had the same issue since yesterday

- SonarQube Community Edition:  v10.4
- Plugin: 1.20
- Github cloud

**Comment by vernigora2** [comment]
We've had the same issue since yesterday

SonarQube Community Edition: v9.9
Plugin: 1.14
Github cloud

**Comment by ashishvaishno** [comment]
We also seen issue since yesterday 
SonarQube Community Edition: 10.2.1
Plugin version : 1.17.1

**Comment by kasparsginters** [comment]
Same issue.
On-prem
SonarQube Community Edition: 10.5.1
Plugin version : 1.19.1
GitHub: Cloud

**Comment by tico24** [comment]
It's fairly obvious by now that this is a widespread issue. Please strongly consider just adding your thumb to the issue rather than sending these messages to everyone watching the issue.

**Comment by stefan-toubia** [comment]
We found that we had to use block strings `"""` for multiline text

**Comment by mc1arke** [comment]
I've proposed a fix in #961 which works for some local integration tests. It would be useful if anyone who is encountering this issue could try using the snapshot attached to the MRs pipeline to see if the fix resolves their issue. Once I have some confirmation that this works then I'll aim to get a release of the plugin out and the fix back-ported to the LTS-compatible version of the plugin.

**Comment by 99Arrzel** [comment]
Having same problem on self hosted

**Comment by kienw** [comment]
> I've proposed a fix in #961 which works for some local integration tests. It would be useful if anyone who is encountering this issue could try using the snapshot attached to the MRs pipeline to see if the fix resolves their issue. Once I have some confirmation that this works then I'll aim to get a release of the plugin out and the fix back-ported to the LTS-compatible version of the plugin.

@mc1arke I have tried out the snapshot.
I got the snapshot from [build / snapshot (17) (pull_request)](https://github.com/mc1arke/sonarqube-community-branch-plugin/actions/runs/10690893309/job/29636268341?pr=961):
> Artifact download URL: https://github.com/mc1arke/sonarqube-community-branch-plugin/actions/runs/10690893309/artifacts/1888225789

I upgraded my SonarQube version from `10.5` to `10.6`, then install this snapshot plugin.
It works! 🎉 
Thanks! ❤️ 

Note: At first, I upgraded the plugin from `1.19.0` to the snapshot version on my SonarQube version `10.5`, and I encountered the issue where the `ElasticSearch` keeps failing, and I had to restore the SonarQube VM from the backup.
I wonder if it is because the plugin version is not compatible with SonarQube version `10.5`, any idea?

**Comment by kasparsginters** [comment]
Did the same as @kienw 
Using docker to run SonarQube and PostgreSQL.

Bumped SonarQube 10.5-community to 10.6-community before applying `sonarqube-community-branch-plugin-1.22.0-SNAPSHOT.jar`

PR decorations working.

Thank you!

**Comment by Tsuesun** [comment]
FYI, I got this response from Github support
```
<snip>
Numerous customers have reached out in the last 24 hours highlighting similar behaviour, so we've gone ahead and raised this with our engineering team for further analysis. Hopefully, they'll be able to shed some light on this in the coming days and we'll update you as soon as news becomes available. Marking this case as On-Hold for now as it's sitting with another team to address.
```

**Comment by mc1arke** [comment]
Released in 1.22.0

**Comment by smukarramhs** [comment]
@mc1arke can this also be released in the LTS supported version which is 1.14.0 please?

**Comment by NamanNacedo** [comment]
if I update sonarqube community edition it will solve this issue? or if I just update to the LTA it will work?

**Comment by visu-suganya** [comment]
@mc1arke Now the issue got fixed automatically in 9.9LTA and 10.2 versions without updating the plugin.
I wonder what is the reason behind this?

**Comment by azun-c** [comment]
Is there something changed on Github side?

https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/959#issuecomment-2330406190

**Comment by fegbers** [comment]
We have not adjusted anything either. GitHub has apparently made adjustments

**Comment by fegbers** [comment]
The problem is back... Is anyone else affected by this?

**Comment by mc1arke** [comment]
@fegbers Can you share what version of the plugin you're running, and a debug log showing your request and response if possible please?

**Comment by fegbers** [comment]
@mc1arke I think the problem was caused by [GitHub](https://www.githubstatus.com/incidents/kv1lzpgzr9yp). Now the problem can no longer be reproduced. Thank you for your quick response.

**Comment by revanth-svmx** [comment]
@mc1arke I'm seeing this issue
