### ISSUE TITLE
Test seems to be rely on local setup timezone

### ISSUE THREAD

**Issue by kakawait** [mc1arke/sonarqube-community-branch-plugin#972]
**Describe the bug**

```bash
git clone https://github.com/mc1arke/sonarqube-community-branch-plugin.git
cd sonarqube-community-branch-plugin
./gradlew clean build
```

And get

```
ListActionTest > shouldExecuteRequestWithValidParameter() FAILED
    java.lang.AssertionError at ListActionTest.java:189
```

See report below

```
java.lang.AssertionError: 
Expecting actual:
  pullRequests {
  key: "prKey"
  title: "title"
  branch: "prBranch"
  base: "branch2Key"
  status {
    qualityGateStatus: "live measure"
  }
  url: "url"
  target: "target"
}
pullRequests {
  key: "prKey2"
  title: "title2"
  branch: "prBranch2"
  status {
  }
  isOrphan: true
  analysisDate: "2009-02-14T00:31:31+0100"
  url: "url2"
}
pullRequests {
  key: "prKey3"
  title: "title3"
  branch: "prBranch2"
  base: "branch2Key"
  status {
  }
  url: "url3"
  target: "branch2Key"
}
pullRequests {
  key: "prKey4"
  base: "branch2Key"
  status {
  }
  target: "branch2Key"
}

to be equal to:
  pullRequests {
  key: "prKey"
  title: "title"
  branch: "prBranch"
  base: "branch2Key"
  status {
    qualityGateStatus: "live measure"
  }
  url: "url"
  target: "target"
}
pullRequests {
  key: "prKey2"
  title: "title2"
  branch: "prBranch2"
  status {
  }
  isOrphan: true
  analysisDate: "2009-02-13T23:31:31+0000"
  url: "url2"
}
pullRequests {
  key: "prKey3"
  title: "title3"
  branch: "prBranch2"
  base: "branch2Key"
  status {
  }
  url: "url3"
  target: "branch2Key"
}
pullRequests {
  key: "prKey4"
  base: "branch2Key"
  status {
  }
  target: "branch2Key"
}

when recursively comparing field by field, but found the following difference:

field/property 'pullRequests_[1].analysisDate_' differ:
- actual value  : "2009-02-14T00:31:31+0100"
- expected value: "2009-02-13T23:31:31+0000"

The recursive comparison was performed with this configuration:
- no equals methods were used in the comparison EXCEPT for java JDK types since introspecting JDK types is forbidden in java 17+ (use withEqualsForType to register a specific way to compare a JDK type if you need it)
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
  - java.nio.file.Path -> lexicographic comparator (Path natural order)
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).
- the introspection strategy used was: DefaultRecursiveComparisonIntrospectionStrategy

	at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListActionTest.shouldExecuteRequestWithValidParameter(ListActionTest.java:189)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

---

**Software Versions**
 - Plugin Version: 5932956c296af3b79739897d0c7676f9d4d4b92d

**Additional context**

I'm GMT+02

**Comment by mc1arke** [comment]
Fix merged. Please let me know if you encounter issues in any other tests

**Comment by kakawait** [comment]
Confirmed!

```
BUILD SUCCESSFUL in 19s
8 actionable tasks: 8 executed
```

Thank you
