### ISSUE TITLE
10.7 upgrade

### ISSUE THREAD

**Issue by kakawait** [mc1arke/sonarqube-community-branch-plugin#976]
10.6 Sonarqube version has following bug https://sonarsource.atlassian.net/browse/SONAR-22149 that prevent displaying image from Sonaqube server

Resulting

![Screenshot 2024-10-08 at 15 50 29](https://github.com/user-attachments/assets/01f10e8c-629c-4d60-8dec-6fe4cac038f8)

Can we release new version of plugin for 10.7?

I've tried on my fork, 10.7 is just _bump number_ version, no breaking change on API and other.
That why I didn't propose PR because is it will more about releasing process rather than coding value.

PS: with 10.7 version icon from report is correctly fixed

**Comment by brother** [comment]
Does the plugin work properly on 10.7? 
If that's the case I don't see what you need from a new version of the plugin, the version matrix on the readme need to be updated but that could probably be handled without a proper release.

**Comment by kakawait** [comment]
Yes it works. Is more about releasing new docker image https://hub.docker.com/r/mc1arke/sonarqube-with-community-branch-plugin

I know we can use official sonarqube docker image but this plugin image is really simpler to use

**Comment by mc1arke** [comment]
> Well, it works, but the report key for Code Insights has changed

This was called out in the release note (copied below), and isn't relevant to whether the plugin works on 10.7, given the same bahviour is exhibited on 10.6:
> #934: Use static report key for non-monorepo Bitbucket decoration by @mc1arke in #951

**Comment by sephiroth-j** [comment]
Okay, thanks for the clarification. We updated from Sonar 10.6. to 10.7 and at the same time updated the plugin from 1.21 to 1.22 and did not correctly assess the impact of this change.

**Comment by tejas-dhamdhere** [comment]
Hello @mc1arke  

Could you please check and confirm plugin version 1.22.0 is supported (working properly)for Sonarqube version 10.7 and update version matrix on the readme

**Comment by brother** [comment]
I am using 1.22.0 + 10.7 fine for our platform.

README need updates ofc.

**Comment by naofireblade** [comment]
I m using 1.22.0 + 10.7 with GitLab MR decoration without problems.

**Comment by 99Arrzel** [comment]
Trying to accomplish this with Github
PR is not working

Looks like github api has a typo
```
sonarqube  | java.lang.IllegalStateException: Could not decorate Pull Request on Github
sonarqube  |    at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:96)
sonarqube  |    at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:139)
sonarqube  |    at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:101)
sonarqube  |    at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:92)
sonarqube  |    at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:89)
sonarqube  |    at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:61)
sonarqube  |    at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
sonarqube  |    at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
sonarqube  |    at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
sonarqube  |    at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
sonarqube  |    at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
sonarqube  |    at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
sonarqube  |    at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
sonarqube  |    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
sonarqube  |    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
sonarqube  |    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
sonarqube  |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
sonarqube  |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
sonarqube  |    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
sonarqube  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
sonarqube  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
sonarqube  |    at java.base/java.lang.Thread.run(Unknown Source)
sonarqube  | Caused by: java.lang.IllegalStateException: An error was returned in the response from the Github API:
sonarqube  | - Error{message='InputObject 'UpdateCheckRunInput' doesn't accept argument 'headSha'', locations=[Location{line='20', column='8291'}]}
sonarqube  |    at com.github.mc1arke.sonarqube.plugin.almclient.github.v4.GraphqlGithubClient.executeRequest(GraphqlGithubClient.java:246)
sonarqube  |    at com.github.mc1arke.sonarqube.plugin.almclient.github.v4.GraphqlGithubClient.reportRemainingAnnotations(GraphqlGithubClient.java:280)
sonarqube  |    at com.github.mc1arke.sonarqube.plugin.almclient.github.v4.GraphqlGithubClient.createCheckRun(GraphqlGithubClient.java:112)
sonarqube  |    at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.github.GithubPullRequestDecorator.decorateQualityGateStatus(GithubPullRequestDecorator.java:88)

```
